FROM registry.fedoraproject.org/fedora:43

RUN dnf install --setopt=install_weak_deps=False --nodocs -y \
    adwaita-cursor-theme \
    adwaita-icon-theme \
    alsa-utils \
    bash-completion \
    dbus-daemon \
    fira-code-fonts \
    foot \
    grim \
    htop \
    imv \
    libevdev \
    libinput \
    libseat \
    mako \
    mesa-dri-drivers \
    mesa-libEGL \
    mesa-libGL \
    mesa-libgbm \
    mesa-vulkan-drivers \
    neovim \
    pipewire \
    pipewire-alsa \
    pipewire-pulseaudio \
    kanshi \
    procps-ng \
    slurp \
    sudo \
    swappy \
    swayidle \
    swaylock \
    systemd \
    systemd-udev \
    util-linux \
    wayfire \
    wayfire-config-manager \
    wdisplays \
    wf-recorder \
    wf-shell \
    wireplumber \
    wl-clipboard \
    wlr-randr \
    wofi \
    xorg-x11-server-Xwayland \
    && dnf clean all

# Wayfire config
COPY --link --chmod=0644 wayfire.ini /etc/xdg/wayfire.ini
COPY --link --chmod=0644 foot.ini /etc/xdg/foot/foot.ini

# Audio startup script and PipeWire ALSA sink config
COPY --link --chmod=0755 start-audio.sh /etc/xdg/wayfire/start-audio.sh

# systemd services
COPY --link --chmod=0644 systemd/wayfire.service /usr/lib/systemd/system/wayfire.service
RUN mkdir -p /etc/systemd/system && \
    ln -sf /dev/null /etc/systemd/system/systemd-udevd.service && \
    ln -sf /dev/null /etc/systemd/system/systemd-udevd-control.socket && \
    ln -sf /dev/null /etc/systemd/system/systemd-udevd-kernel.socket && \
    systemctl enable wayfire

STOPSIGNAL SIGRTMIN+3
CMD ["/usr/sbin/init"]
