FROM registry.fedoraproject.org/fedora:43

RUN dnf install --setopt=install_weak_deps=False --nodocs -y \
    adwaita-cursor-theme \
    adwaita-icon-theme \
    bash-completion \
    cliphist \
    dbus-daemon \
    fira-code-fonts \
    foot \
    grim \
    htop \
    imv \
    mako \
    mesa-dri-drivers \
    mesa-libEGL \
    mesa-libGL \
    mesa-libgbm \
    mesa-vulkan-drivers \
    neovim \
    procps-ng \
    slurp \
    sudo \
    swappy \
    systemd \
    util-linux \
    wayfire \
    wayfire-config-manager \
    wdisplays \
    wf-shell \
    wf-recorder \
    wl-clipboard \
    wlr-randr \
    wlrctl \
    wofi \
    xorg-x11-server-Xwayland \
    && dnf clean all

# Wayfire config
COPY --link --chmod=0644 wayfire.ini /etc/xdg/wayfire.ini
COPY --link --chmod=0644 foot.ini /etc/xdg/foot/foot.ini

# systemd services
COPY --link --chmod=0644 systemd/wayfire.service /usr/lib/systemd/system/wayfire.service
RUN systemctl enable wayfire

STOPSIGNAL SIGRTMIN+3
CMD ["/usr/sbin/init"]
