FROM registry.fedoraproject.org/fedora:43

RUN dnf install --setopt=install_weak_deps=False --nodocs -y \
    adwaita-cursor-theme \
    adwaita-icon-theme \
    bash-completion \
    dbus-daemon \
    fira-code-fonts \
    foot \
    fuzzel \
    grim \
    htop \
    imv \
    labwc \
    mako \
    mesa-dri-drivers \
    mesa-libEGL \
    mesa-libGL \
    mesa-libgbm \
    mesa-vulkan-drivers \
    neovim \
    procps-ng \
    slurp \
    sudo \
    swappy \
    swaybg \
    systemd \
    util-linux \
    waybar \
    wdisplays \
    wf-recorder \
    wl-clipboard \
    wlr-randr \
    wlrctl \
    xorg-x11-server-Xwayland \
    && dnf clean all

# Labwc config
COPY --link --chmod=0644 labwc-config/rc.xml /etc/xdg/labwc/rc.xml
COPY --link --chmod=0755 labwc-config/autostart /etc/xdg/labwc/autostart
COPY --link --chmod=0644 labwc-config/waybar-config /etc/xdg/waybar/config
COPY --link --chmod=0644 foot.ini /etc/xdg/foot/foot.ini

# systemd services
COPY --link --chmod=0644 systemd/labwc.service /usr/lib/systemd/system/labwc.service
RUN systemctl enable labwc

STOPSIGNAL SIGRTMIN+3
CMD ["/usr/sbin/init"]
