"""
cmd_drift — show diff between generated and deployed unit files.

Generates workload units into a temp dir (using the same workload-generate
script that runs at boot), then diffs against /run/systemd/system to show
what is deployed vs what would be generated from the current TOML configs.
Outputs nothing if units are in sync; exits 1 if drift is detected.
"""

import difflib
import os
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

from vm import (
    VM_INSPECT_POLICY_FILE,
    VM_SOCKET_DIR,
    vm_inspect_policy_text,
    vm_uses_inspect,
)
from workload_lib import (
    GENERATED_BY_RE,
    RUN_TREE_SCANS,
    workload_config_dir,
    workload_config_path,
)


# The generator script location (installed path first, dev checkout fallback)
_GENERATOR_CANDIDATES = [
    Path("/usr/libexec/workloadctl/workload-generate"),
    Path(__file__).parent.parent / "generators" / "workload-generate",
]

LIVE_UNITS_DIR = Path("/run/systemd/system")

# Where the inspectors' policy documents live. A module-level name for the same
# reason LIVE_UNITS_DIR is one: it is the root the tests stage instead of.
POLICY_ROOT = VM_SOCKET_DIR


def _find_generator() -> Path:
    for p in _GENERATOR_CANDIDATES:
        if p.is_file():
            return p
    raise RuntimeError(
        "workload-generate script not found. Is workloadctl installed?"
    )


def collect_drift(workload_name=None) -> list:
    """Return the drift set as a list of (filename, live_text, gen_text).

    Runs the generator into a scratch dir and compares its output against
    LIVE_UNITS_DIR without touching either. Raises RuntimeError if the
    generator is missing or fails. Shared by cmd_drift and doctor.
    """
    generator = _find_generator()

    with tempfile.TemporaryDirectory(prefix="workload-drift-") as tmpdir:
        env = {
            **os.environ,
            "WORKLOAD_CONFIG_DIR": str(workload_config_dir()),
            "SYSUSERS_DIR": tmpdir,
        }
        result = subprocess.run(
            [str(generator), tmpdir],
            env=env,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"generator failed:\n{result.stderr.strip()}"
            )

        gen_dir = Path(tmpdir)

        # The generator embeds the services output dir into the sysusers ExecStart
        # path.  Normalize it to the canonical live path so the diff only shows
        # real content changes, not the temp-dir artifact.
        _tmpdir_prefix = tmpdir + "/"
        _live_prefix = str(LIVE_UNITS_DIR) + "/"

        def _normalize(text: str) -> str:
            # Strip the build identity out of the provenance stamp before
            # comparing. drift answers "do the running units match what this
            # TOML would produce"; which build wrote them is a different
            # question, answered by units_from_other_build() and reported on its
            # own line. Leaving the stamp in would mark *every* workload as
            # drifted after *every* RPM upgrade, including the ones whose unit
            # body is byte-identical — which is how a signal stops being read.
            text = GENERATED_BY_RE.sub("# Generated by workload-generate", text)
            return text.replace(_tmpdir_prefix, _live_prefix)

        def _in_scope(rel: Path, scan) -> bool:
            # With no --workload filter every run-file is in scope. Drop-ins are
            # keyed by UID (name_filtered False), so the name filter can't apply
            # to them either — they are always compared. Otherwise keep
            # workload-NAME.service and workload-NAME-*.service (the main unit and
            # its per-container/helper units + sysusers .conf + wants symlink).
            if not workload_name or not scan.name_filtered:
                return True
            return (
                rel.stem == f"workload-{workload_name}"
                or rel.stem.startswith(f"workload-{workload_name}-")
            )

        diffs = []  # list of (filename, live_text, gen_text)

        # One pass per run-file kind (RUN_TREE_SCANS is the single source of which
        # kinds land in this tree), each comparing generated-vs-live in both
        # directions. Forward catches content drift and owned-but-missing files;
        # the orphan sweep catches live run-files a removed/partially-disabled
        # workload stranded in the tmpfs. Reporting every kind keeps "No drift
        # detected" from being a false all-clear.
        for scan in RUN_TREE_SCANS:
            gen_rels = set()
            for gen_file in sorted(gen_dir.glob(scan.glob)):
                rel = gen_file.relative_to(gen_dir)
                if not _in_scope(rel, scan):
                    continue
                gen_rels.add(rel)
                live_file = LIVE_UNITS_DIR / rel
                if scan.content:
                    gen_text = _normalize(gen_file.read_text())
                    # Both sides: the tmpdir artifact only ever appears on the
                    # generated side, but the *stale* build stamp only ever
                    # appears on the live one.
                    live_text = (
                        _normalize(live_file.read_text())
                        if live_file.exists() else ""
                    )
                    if gen_text != live_text:
                        diffs.append((str(rel), live_text, gen_text))
                else:
                    # Enablement symlink: the only drift is presence. is_symlink()
                    # covers a *dangling* live link (target removed out from under
                    # it) — the link file is present, so enablement is not
                    # "missing" even though exists() follows it and returns False.
                    if not (live_file.exists() or live_file.is_symlink()):
                        target = os.readlink(gen_file) if gen_file.is_symlink() else ""
                        diffs.append((
                            str(rel), "",
                            f"# missing enablement symlink -> {target}\n",
                        ))

            if not LIVE_UNITS_DIR.is_dir():
                continue
            for live_file in sorted(LIVE_UNITS_DIR.glob(scan.glob)):
                rel = live_file.relative_to(LIVE_UNITS_DIR)
                if not _in_scope(rel, scan) or rel in gen_rels:
                    continue
                if scan.content:
                    diffs.append((str(rel), live_file.read_text(), ""))
                else:
                    target = os.readlink(live_file) if live_file.is_symlink() else ""
                    diffs.append((
                        str(rel),
                        f"# orphaned enablement symlink -> {target}\n",
                        "",
                    ))

    return diffs


def _rendered_policy(name: str) -> str:
    """What this workload's policy document would be, or "" if it has none.

    "" is the orphan case and covers both of its shapes: the workload was
    removed from the config dir, and the workload is still configured but is no
    longer inspected (`egress` opened, or a bridge added). Both leave a document
    in /run that nothing will rewrite -- `down` does not delete it -- and both
    have to be reported, because an operator reading a stale document has no
    way to tell it from a live one.
    """
    path = workload_config_path(name)
    if not path.is_file():
        return ""
    try:
        with open(path, "rb") as f:
            config = tomllib.load(f)
    except (OSError, tomllib.TOMLDecodeError) as e:
        # Loud rather than skipped. A config that will not parse is exactly the
        # state in which the document on disk is least likely to match it, and
        # silently omitting the workload would make "No drift detected" a false
        # all-clear for the one workload most likely to have drifted.
        raise RuntimeError(f"could not read {path}: {e}") from None
    if not vm_uses_inspect(config):
        return ""
    return vm_inspect_policy_text(config.get("vm", {}).get("network", {}) or {})


def collect_policy_drift(workload_name=None) -> list:
    """Policy-document drift as [(filename, live_text, gen_text)].

    The same caller-facing shape as collect_drift, so cmd_drift and doctor
    render it with the unified diff they already have. It is a separate
    collector rather than another RUN_TREE_SCANS row because both halves
    differ: the producer is `workload-vm-inspect up` at service start rather
    than the boot generator, and the root is /run/workload-vm rather than the
    unit tree, so collect_drift's generator-into-a-scratch-dir mechanism cannot
    reach this file at all.

    THE SCAN IS DRIVEN BY WHAT IS ON DISK, not by what is configured. An
    inspected workload that has never started this boot has no document, and
    that is not drift -- it is the ordinary state of a stopped VM, and
    reporting it would mark every stopped workload as drifted forever. What a
    present document means is that some listener start rendered it, so a
    difference against a re-render is the actionable condition detail §7.7
    names: an inspector still enforcing the policy the previous start read.
    The remedy is a restart, not a regenerate, which is why cmd_drift prints a
    different remedy for these.
    """
    diffs = []
    # glob() on a root that does not exist yields nothing rather than raising,
    # which is the wanted answer for a host that has never started a VM — so
    # there is no is_dir() guard to go stale.
    root = Path(POLICY_ROOT)
    for policy_file in sorted(root.glob(f"*/{VM_INSPECT_POLICY_FILE}")):
        name = policy_file.parent.name
        if workload_name and name != workload_name:
            continue
        try:
            live_text = policy_file.read_text()
        except OSError as e:
            raise RuntimeError(f"could not read {policy_file}: {e}") from None
        gen_text = _rendered_policy(name)
        if live_text != gen_text:
            diffs.append((f"{name}/{VM_INSPECT_POLICY_FILE}", live_text, gen_text))
    return diffs

def cmd_drift(args, manager):
    """Show diff between TOML-generated units and running units.

    Runs the generator in a scratch directory and diffs the output against
    /run/systemd/system.  No changes are applied.  Exits 1 if drift exists,
    0 if everything is in sync.
    """
    workload_name = getattr(args, "workload", None)
    json_output = getattr(args, "json", False)

    try:
        diffs = collect_drift(workload_name)
        policy_diffs = collect_policy_drift(workload_name)
    except RuntimeError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    def _render(fname, live_text, gen_text):
        from_label = f"running/{fname}" if live_text else "/dev/null"
        to_label = f"generated/{fname}" if gen_text else "/dev/null"
        return list(difflib.unified_diff(
            live_text.splitlines(keepends=True),
            gen_text.splitlines(keepends=True),
            fromfile=from_label,
            tofile=to_label,
        ))

    if json_output:
        import json
        out = [{"unit": fname, "drifted": True,
                "diff": "".join(_render(fname, live_text, gen_text))}
               for fname, live_text, gen_text in diffs]
        # A separate key rather than another "units" row: these are not units,
        # the remedy is a restart rather than a regenerate, and a consumer that
        # fed this list to `systemctl daemon-reload` would be acting on the
        # wrong noun. "drifted" spans both, so a reader that only checks the
        # boolean is still right.
        docs = [{"document": fname, "drifted": True,
                 "diff": "".join(_render(fname, live_text, gen_text))}
                for fname, live_text, gen_text in policy_diffs]
        print(json.dumps({
            "drifted": bool(out or docs),
            "units": out,
            "documents": docs,
        }, indent=2))
        sys.exit(1 if (out or docs) else 0)

    if not diffs and not policy_diffs:
        print("No drift detected — running units match generated output")
        sys.exit(0)

    for fname, live_text, gen_text in diffs:
        sys.stdout.writelines(_render(fname, live_text, gen_text))
        print()

    for fname, live_text, gen_text in policy_diffs:
        sys.stdout.writelines(_render(fname, live_text, gen_text))
        print()

    # Named separately because the remedy differs. The unit tree is fixed by
    # regenerating; a policy document is written by the inspect socket's
    # ExecStartPre and read once by the listener at start, so nothing short of
    # restarting that socket applies an edited [vm.network] table.
    for fname, _live, _gen in policy_diffs:
        name = fname.split("/", 1)[0]
        print(f"# {fname} is the inspector's loaded policy — apply the config "
              f"with:\n#   systemctl restart workload-{name}-inspect.socket")

    sys.exit(1)
