"""
The per-workload files a workload owns: the list, the scan, and the stamp.

The single source of truth for which units, symlinks, sysusers fragments,
drop-ins and env-files exist for a workload -- see docs/workload-run-files.md
for the authoritative table and rationale -- plus the provenance stamp the
generator writes into each and the checks that read it back.
"""
import os
import re
from dataclasses import dataclass
from pathlib import Path

from broker_config import container_uses_credentials, vm_uses_credentials
from container_network_config import container_uses_inspect
from egress_policy import (
    container_uses_resolve, vm_uses_resolve, vm_uses_inspect,
)
from workload_lib import (
    RUN_SYSTEMD_SYSTEM, WORKLOADCTL_VERSION, virtiofs_tags,
    workload_config_path, workload_service_name,
)

# Provenance comment carried by every file the generator emits. The version in
# parentheses is what makes "these units were generated by an older workloadctl"
# detectable — units live in /run and are only rewritten at boot or by `enable`,
# so an RPM upgrade on a package host leaves running workloads on the previous
# generator's output with nothing to say so. `units_outdated()` cannot see it
# (it compares mtimes, and the TOML did not change); `drift` normalizes it away
# on purpose (see cmd_drift._normalize) so a build bump does not mark every
# workload as content-drifted.
GENERATED_BY = f"Generated by workload-generate ({WORKLOADCTL_VERSION})"

# Matches the stamp anywhere in a unit's preamble — the cgroup drop-in carries a
# workload-specific first line, so it is not always line 1. The unversioned form
# is deliberately matched too: units written by a pre-stamp build have to be
# recognisable as such, since that upgrade is exactly the one this detects.
GENERATED_BY_RE = re.compile(
    r"^#\s*Generated by workload-generate(?: \(([^)]*)\))?", re.MULTILINE
)



# --- Workload run-files (B15) ---------------------------------------------- #
#
# The single source of truth for "the per-workload files a workload owns" — see
# docs/workload-run-files.md for the authoritative table and rationale.
#
# Every caller slices this one list along whichever axis it cares about, instead
# of re-deriving the set:
#   * emitted view (rf.emitted True) — files that exist for THIS exact config;
#     used by the generator-parity oracle, drift, inspect, and metrics.
#   * removable superset (all kinds but env-file) — the mode-family union the
#     disable/purge path may safely unlink() with missing_ok; over-lists -pod/-net
#     for every container workload so disabling can never miss a topology's unit.
#   * env-tree files (kind == 'env-file') — the runtime-written .env/.secrets that
#     only --purge removes.
# Filter by `kind` for tree/lifecycle and by `role` for a specific unit family.

def workload_env_dir() -> Path:
    """Runtime env tree (.env/.secrets). Honors WORKLOAD_ENV_DIR for tests."""
    return Path(os.environ.get("WORKLOAD_ENV_DIR", "/run/workload-env"))


@dataclass(frozen=True)
class WorkloadRunFile:
    """One file a workload owns, tagged so every caller can filter one list.

    kind  — which tree + removal lifecycle it belongs to:
            'unit' | 'wants-symlink' | 'sysusers' | 'dropin' | 'env-file'.
    role  — which unit family, for callers that want a specific member:
            'main' | 'setup' | 'build' | 'pod' | 'net' | 'container' |
            'virtiofs' | 'sysusers' | 'dropin' | 'env' | 'secrets'.
    emitted — True iff the generator writes this file for THIS config (the
            emitted view). False marks the removable-only superset entries
            (-pod/-net listed for non-matching modes) and the runtime-written
            env-files the generator never produces.
    """

    path: Path
    kind: str
    role: str
    emitted: bool


def workload_run_files(config) -> list[WorkloadRunFile]:
    """The complete set of run-files owned by one workload.

    MUST stay in sync with generators/workload-generate (generate_*_workload) and
    with the removal path. Never includes shared infra (workload-generate.service)
    or references to *other* workloads' units. VM workloads no longer contribute
    any shared unit at all: retiring the managed bridge (ADR 006) removed the one
    host-global unit the generator materialized as a side effect of the first VM.

    Superset semantics: -pod.service and -net.service are listed for every
    container workload (emitted only for the matching mode) so the removable view
    can unlink() the full topology with missing_ok. The cgroup drop-in is keyed by
    the workload UID from the passwd db; if the user is gone the UID can't be
    reconstructed, so it is omitted rather than raising.
    """
    # Lazy import: workloadctl_core imports this module, so a top-level import
    # would be circular.
    from workloadctl_core import WorkloadUserNotFound

    run = RUN_SYSTEMD_SYSTEM
    env = workload_env_dir()
    name = config.name
    files: list[WorkloadRunFile] = [
        WorkloadRunFile(run / f"workload-{name}.conf", "sysusers", "sysusers", True),
        WorkloadRunFile(run / f"workload-{name}-setup.service", "unit", "setup", True),
        WorkloadRunFile(run / f"workload-{name}.service", "unit", "main", True),
        WorkloadRunFile(
            run / "multi-user.target.wants" / f"workload-{name}.service",
            "wants-symlink", "main", True,
        ),
    ]

    if config.is_vm:
        files.append(
            WorkloadRunFile(run / f"workload-{name}-build.service", "unit", "build", True)
        )
        # The clock keeper, for every VM without a predicate: it is about
        # the guest's clock and not its egress, so a bridged VM has one too.
        files.append(WorkloadRunFile(
            run / f"workload-{name}-clock.timer", "unit", "clock-timer", True
        ))
        files.append(WorkloadRunFile(
            run / f"workload-{name}-clock.service", "unit", "clock", True
        ))
        for tag in virtiofs_tags(config.config.get("vm", {}).get("volumes", [])):
            files.append(WorkloadRunFile(
                run / f"workload-{name}-virtiofs-{tag}.service", "unit", "virtiofs", True
            ))
        # The retired hostname-policy proxy, listed with present=False and
        # generated by nothing. This is not superset semantics -- it is a
        # MIGRATION entry, and the distinction matters to whoever deletes it.
        #
        # /run/systemd/system is tmpfs, so a reboot clears the stale unit on its
        # own. An in-place RPM upgrade does not: the previous version's
        # workload-<name>-proxy.service is still on disk and still running a
        # tinyproxy this version has stopped packaging, and without this line
        # `workloadctl remove` would leave it behind with nothing that knows its
        # name. Listing it is what lets the removable view unlink it.
        #
        # Safe to delete once every host has rebooted past the rung-2 upgrade.
        files.append(WorkloadRunFile(
            run / f"workload-{name}-proxy.service", "unit", "proxy", False,
        ))
        # Superset semantics, like -pod/-net for containers: always listed so
        # the removable view unlinks them, emitted only when
        # egress inspection applies (not bridged, egress filtered). The socket
        # unit owns the arming — it binds its ListenStream= before the service
        # ever runs — and the service owns the process and its cgroup
        # exemptions.
        # G3 in the container egress-parity build spec: VM-only by
        # construction -- this whole block is inside `if config.is_vm:`. The
        # container `else` branch below carries its own container_inspects,
        # sourced from container_uses_inspect (P1-7..P1-9).
        vm_inspects = vm_uses_inspect(config.config)
        files.append(WorkloadRunFile(
            run / f"workload-{name}-inspect.socket", "unit", "inspect-socket",
            vm_inspects,
        ))
        files.append(WorkloadRunFile(
            run / f"workload-{name}-inspect.service", "unit", "inspect",
            vm_inspects,
        ))
        # The synthesising responder, on the same superset terms one predicate
        # further in: everything the inspector needs, plus `resolver` not being
        # "none". Listed unconditionally so a workload that switches the knob
        # off has its stale units unlinked rather than left behind answering
        # for a guest that was told to ask nobody.
        vm_resolves = vm_uses_resolve(config.config)
        files.append(WorkloadRunFile(
            run / f"workload-{name}-resolve.socket", "unit", "resolve-socket",
            vm_resolves,
        ))
        files.append(WorkloadRunFile(
            run / f"workload-{name}-resolve.service", "unit", "resolve",
            vm_resolves,
        ))
        # The credential broker instance, superset semantics again: listed for
        # every VM so a workload that drops its last credential has the unit
        # unlinked rather than left behind holding material nothing selects,
        # and emitted only when the workload declares one AND is inspected.
        #
        # Being an ordinary run-file is most of why the design chose a full
        # generated unit here: `drift` compares it against a fresh render with
        # no machinery of its own, and a broker instance whose unit has
        # silently diverged from the bundle is a credential-SELECTION bug --
        # the wrong key on the wrong host, on the one path that carries a real
        # one.
        files.append(WorkloadRunFile(
            run / f"workload-{name}-broker.service", "unit", "broker",
            vm_uses_credentials(config.config),
        ))
    else:
        # cgroup-placement drop-in (containers only). Keyed by the workload UID
        # from the passwd db; omitted once the user is gone (UID unreconstructable).
        # A pure query helper must not allocate a UID.
        try:
            files.append(WorkloadRunFile(
                run / f"user@{config.uid}.service.d" / "50-workload.conf",
                "dropin", "dropin", True,
            ))
        except WorkloadUserNotFound:
            pass
        mode = config.mode
        files.append(WorkloadRunFile(
            run / f"workload-{name}-pod.service", "unit", "pod", mode == "pod"
        ))
        files.append(WorkloadRunFile(
            run / f"workload-{name}-net.service", "unit", "net", mode == "bridge"
        ))
        # Per-container units key on topology, matching the generator and the
        # -pod/-net gates above; the per-container .secrets below key on the same
        # `mode != "single"` so disable/purge lists units and secrets together.
        if mode != "single":
            for cname in config.container_names():
                files.append(WorkloadRunFile(
                    run / f"workload-{name}-{cname}.service", "unit", "container", True
                ))
        # Container counterpart of the VM inspect-socket/service pair above
        # (P1-9). Superset semantics, same as -pod/-net: always listed so the
        # removable view unlinks stale units, emitted only when
        # container_uses_inspect() fires.
        container_inspects = container_uses_inspect(config.config)
        files.append(WorkloadRunFile(
            run / f"workload-{name}-inspect.socket", "unit", "inspect-socket",
            container_inspects,
        ))
        files.append(WorkloadRunFile(
            run / f"workload-{name}-inspect.service", "unit", "inspect",
            container_inspects,
        ))
        # The responder pair, superset semantics as the VM's: listed for
        # every container so a workload that moves to bridge mode or drops
        # its last trigger has its stale units unlinked.
        container_resolves = container_uses_resolve(config.config)
        files.append(WorkloadRunFile(
            run / f"workload-{name}-resolve.socket", "unit", "resolve-socket",
            container_resolves,
        ))
        files.append(WorkloadRunFile(
            run / f"workload-{name}-resolve.service", "unit", "resolve",
            container_resolves,
        ))
        # The credential broker instance (P2-4), superset semantics again and
        # for the reason G16 flagged: listed for every container so a workload
        # that drops its last credential has the unit unlinked rather than
        # left behind holding material nothing selects -- invisible to `drift`
        # and `disable` otherwise. The `present=` is the same predicate the
        # generator emits on, so the two cannot disagree.
        files.append(WorkloadRunFile(
            run / f"workload-{name}-broker.service", "unit", "broker",
            container_uses_credentials(config.config),
        ))

    # Runtime-written env tree — never produced by the generator (emitted False),
    # removed only on --purge. .secrets is over-listed per container (missing_ok).
    files.append(WorkloadRunFile(env / f"workload-{name}.env", "env-file", "env", False))
    files.append(
        WorkloadRunFile(env / f"workload-{name}.secrets", "env-file", "secrets", False)
    )
    # Per-container .secrets gate on the SAME discriminator as the per-container
    # units above (mode != "single"), not is_multi — a split discriminator here
    # strands loaded units when the two disagree (cmd_disable would unlink these
    # .secrets but never list the matching .service units). Correctly False for
    # VMs too (mode "single"; they own no per-container secrets).
    if config.mode != "single":
        for cname in config.container_names():
            files.append(WorkloadRunFile(
                env / f"workload-{name}-{cname}.secrets", "env-file", "secrets", False
            ))

    return files


@dataclass(frozen=True)
class RunTreeScan:
    """How to find one run-file kind when scanning the whole run tree.

    Companion to workload_run_files(): that lists the files ONE config owns;
    this lists the glob per kind so a tree-walker (workloadctl drift) can compare
    generated-vs-live for every workload at once, in both directions, without
    re-deriving the workload-<name>* name formulas. Kinds mirror
    WorkloadRunFile.kind for the files that land under RUN_SYSTEMD_SYSTEM — the
    env-file kinds live in the env tree and never appear here.

    glob          — pattern under the run root (drift's scratch dir or the live
                    tree); may descend a subdir (wants/, user@*.service.d/).
    content       — True: drift is a byte diff of the file. False: the file is an
                    enablement symlink whose only drift is presence/absence.
    name_filtered — True: the file is named workload-<name>* so `drift <name>`
                    can scope to it. False: drop-ins are keyed by UID, so the
                    name filter can't apply and they are always in scope.
    """

    kind: str
    glob: str
    content: bool
    name_filtered: bool


# Every run-file kind that lands under RUN_SYSTEMD_SYSTEM, as a scan table for
# drift. Adding a kind here (alongside its workload_run_files entry) is all drift
# needs to start comparing it — there is no per-kind block to duplicate.
# test_run_tree_scans_cover_run_files pins this to workload_run_files' tree kinds.
RUN_TREE_SCANS: list[RunTreeScan] = [
    RunTreeScan("unit", "workload-*.service", content=True, name_filtered=True),
    RunTreeScan("unit", "workload-*.socket", content=True, name_filtered=True),
    RunTreeScan("sysusers", "workload-*.conf", content=True, name_filtered=True),
    RunTreeScan(
        "wants-symlink",
        "multi-user.target.wants/workload-*.service",
        content=False,
        name_filtered=True,
    ),
    RunTreeScan(
        "dropin",
        "user@*.service.d/50-workload.conf",
        content=True,
        name_filtered=False,
    ),
]


def workload_service_units(config, *, roles=None) -> list[str]:
    """Emitted systemd .service unit names for THIS config.

    A convenience view over workload_run_files(): the services the generator
    actually writes — main, setup, the matching pod/net helper or per-container
    services, and for VMs the build and virtiofs units. Pass roles to keep only
    a subset, e.g. roles={"setup", "build"} for a VM's gating units.
    """
    return [
        rf.path.name
        for rf in workload_run_files(config)
        if rf.kind == "unit" and rf.emitted and (roles is None or rf.role in roles)
    ]


def render_sysusers_config(
    *,
    name: str,
    user_name: str,
    uid: int,
    home_dir: str,
    extra_groups=(),
    is_vm: bool = False,
) -> str:
    """Render the systemd-sysusers config for a workload's dedicated user.

    The generator is the sole producer of this .conf: both boot and enable-time
    provisioning go through it (enable consumes the generator's output rather
    than re-rendering — see cmd_lifecycle._generate_units / _provision_user), so
    there is one producer and nothing to drift. UID must be pre-allocated by the
    caller — this is a pure render and never allocates. A VM gets implicit `kvm`
    membership, de-duplicated against extra_groups so it is never emitted twice.
    """
    lines = [
        f"# Workload user for {name}" + (" (VM)" if is_vm else ""),
        f'u {user_name} {uid} "{name} workload" {home_dir}',
    ]
    groups: list[str] = []
    if is_vm:
        groups.append("kvm")
    for group in extra_groups:
        if group not in groups:
            groups.append(group)
    for group in groups:
        lines.append(f"m {user_name} {group}")
    return "\n".join(lines) + "\n"


def units_outdated(name: str) -> bool:
    """True if the workload's config TOML is newer than its generated unit file.

    `systemctl daemon-reload` re-runs the *shell* generator only (which emits a
    boot oneshot), NOT the Python unit-writer — so editing a workload.toml does
    not regenerate the per-workload units until `workloadctl enable <name>` is
    re-run. This mtime comparison is the cheap heads-up for that foot-gun; the
    authoritative content-level check is `workloadctl drift`.

    Returns False if either file is absent (workload never enabled / no config)
    so callers can treat "can't tell" as "nothing to warn about". A 1s slack
    swallows same-second writes from an enable that wrote both.
    """
    try:
        unit_mtime = (RUN_SYSTEMD_SYSTEM / workload_service_name(name)).stat().st_mtime
        config_mtime = workload_config_path(name).stat().st_mtime
    except OSError:
        return False
    return config_mtime > unit_mtime + 1.0


# What unit_generator_version() reports for a unit that carries the provenance
# comment without a version — i.e. one written by a workloadctl older than the
# stamp itself. Truthy, because that is a real "regenerate me" condition and the
# most likely one to be seen in the field exactly once per host.
UNSTAMPED_BUILD = "an unstamped build (pre-versioned units)"


def unit_generator_version(path: Path | str) -> str | None:
    """The workloadctl build that generated the unit file at `path`.

    Returns UNSTAMPED_BUILD when the file carries the provenance comment with no
    version, and None when the file is absent, unreadable, or was not written by
    the generator at all — callers treat None as "nothing to say".

    Only the head of the file is scanned: the stamp lives in the preamble, and a
    generated unit is a few KiB at most.
    """
    try:
        with open(path, "r") as f:
            head = f.read(2048)
    except OSError:
        return None
    match = GENERATED_BY_RE.search(head)
    if match is None:
        return None
    return match.group(1) or UNSTAMPED_BUILD


def units_from_other_build(name: str) -> str | None:
    """The build that generated this workload's live main unit, if not ours.

    The companion to units_outdated(): that one catches "the TOML moved under the
    units", this one catches "the software moved under the units". They are
    independent — an RPM upgrade changes neither file's mtime, and a TOML edit
    does not change the stamp — so both are needed, and the remedy for both is
    the same `workloadctl enable`.

    Returns None when the stamps agree, when the unit does not exist, or when the
    unit predates the generator writing one.
    """
    stamped = unit_generator_version(RUN_SYSTEMD_SYSTEM / workload_service_name(name))
    if stamped is None or stamped == WORKLOADCTL_VERSION:
        return None
    return stamped
