"""
Shared constants and utilities for the workload provisioning system.

Used by workload-generate (the early-boot oneshot Python script),
workload-ensure-user, and workloadctl.
Installed to /usr/libexec/workloadctl/workload_lib.py.
"""

import contextlib
import fcntl
import os
import pwd
import re
import stat
from dataclasses import dataclass
from pathlib import Path


# --- Constants ---

# Build identity. The RPM's %install writes a _version.py sibling of these
# modules (see rpm/workloadctl.spec) carrying the full NEVR; Release is a
# monotonic build serial, so the string is comparable between any two builds.
# Absent from a source checkout and from the test tree, where "0-dev" stands in.
#
# Defined here rather than in bin/workloadctl because three things have to agree
# on one string: `--version`, the provenance stamp the generator writes into
# every unit, and the check that compares a live unit's stamp against the running
# build. Two spellings of the fallback would make a source checkout report itself
# as stale.
try:
    from _version import __version__ as WORKLOADCTL_VERSION
except ImportError:
    WORKLOADCTL_VERSION = "0-dev"

# Provenance comment carried by every file the generator emits. The version in
# parentheses is what makes "these units were generated by an older workloadctl"
# detectable — units live in /run and are only rewritten at boot or by `enable`,
# so an RPM upgrade on a package host leaves running workloads on the previous
# generator's output with nothing to say so. `units_outdated()` cannot see it
# (it compares mtimes, and the TOML did not change); `drift` normalizes it away
# on purpose (see cmd_drift._normalize) so a build bump does not mark every
# workload as content-drifted.
GENERATED_BY = f"Generated by workload-generate ({WORKLOADCTL_VERSION})"

# Matches the stamp anywhere in a unit's preamble — the cgroup drop-in carries a
# workload-specific first line, so it is not always line 1. The unversioned form
# is deliberately matched too: units written by a pre-stamp build have to be
# recognisable as such, since that upgrade is exactly the one this detects.
GENERATED_BY_RE = re.compile(
    r"^#\s*Generated by workload-generate(?: \(([^)]*)\))?", re.MULTILINE
)

# Config directory (override with WORKLOAD_CONFIG_DIR env var for testing)
WORKLOAD_CONFIG_DIR = Path(os.environ.get("WORKLOAD_CONFIG_DIR", "/etc/workloads.d"))


def workload_config_dir() -> Path:
    """Canonical call-time reader for the workloads config dir. Resolves
    WORKLOAD_CONFIG_DIR against this module at call time, so a single
    patch.object(workload_lib, "WORKLOAD_CONFIG_DIR", tmp) is honored everywhere.
    Also re-checks the env var at call time so in-process module loaders that
    set WORKLOAD_CONFIG_DIR in os.environ before exec_module() work correctly."""
    env_val = os.environ.get("WORKLOAD_CONFIG_DIR")
    if env_val:
        return Path(env_val)
    return WORKLOAD_CONFIG_DIR

# Persistent workload data directory
WORKLOADS_BASE = Path("/var/lib/workloads")

# systemd-creds credential store. Secrets are created here (`workloadctl secret`),
# loaded from here by the generator, and decrypted at runtime by
# workload-ensure-user. Single source of truth so backup/restore/rotate can't
# drift onto the wrong path (the plain /etc/credstore is only a legacy fallback).
CREDSTORE_DIR = Path("/etc/credstore.encrypted")

# Shipped bundle control-file tree (Containerfile/build.sh/setup.sh/policy.cil),
# keyed by `[workload] bundle`. Env-overridable so the control-file resolver can
# be unit-tested against a temp /usr tree. The operator override leg lives under
# WORKLOAD_CONFIG_DIR/<name>/ (see WorkloadConfig.resolve_control_file).
WORKLOAD_BUNDLES_DIR = Path(
    os.environ.get("WORKLOAD_BUNDLES_DIR", "/usr/share/workloadctl/workloads")
)

# Username prefix for workload system users
USERNAME_PREFIX = "_wl-"

# [security] key that opts a workload in to `userns = "host"`. Host userns
# dissolves the per-workload isolation boundary, so it is refused unless this is
# set true — an explicit acknowledgement rather than a silently-honoured default.
HOST_USERNS_OPT_IN = "unsafe_host_userns"

# UID range reserved for workload users.
UID_MIN = 10000
UID_MAX = 52948

# Maximum workload name length (32-char Linux username limit - 4-char prefix - 1)
MAX_NAME_LENGTH = 27

# Workload name pattern: lowercase letter, then lowercase letters/digits/hyphens
NAME_PATTERN = re.compile(r'^[a-z][a-z0-9-]*$')

# Container name pattern (same shape as workload name)
CONTAINER_NAME_PATTERN = re.compile(r'^[a-z][a-z0-9-]*$')
MAX_CONTAINER_NAME_LENGTH = 27
VALID_WORKLOAD_MODES = ("single", "pod", "bridge")

# Directives written by the generator — custom_directives should not override these
GENERATOR_OWNED_DIRECTIVES = frozenset({
    "Type", "NotifyAccess", "User", "Group", "Environment", "EnvironmentFile",
    "ExecStartPre", "ExecStart", "ExecStop",
    "StandardOutput", "StandardError",
    "Restart", "RestartSec",
    "ProtectSystem", "ReadWritePaths", "PrivateTmp",
})

# --- Config locator ---

def workload_config_path(name: str) -> Path:
    """Instance config path for a workload, under the config dir."""
    return workload_config_dir() / name / "workload.toml"


# Enabled-ness is denoted by the presence of this marker file in the workload's
# own config dir — NOT by a field in workload.toml. `enable`/`disable` touch and
# unlink it; the boot generator and `WorkloadConfig.enabled` read it. This keeps
# workload.toml purely declarative (no command ever rewrites it) and makes the
# state a single atomic 1-byte file living right beside the config.
ENABLED_MARKER_NAME = ".enabled"


def workload_enabled_marker(name: str) -> Path:
    """Path to a workload's enable marker; its presence == enabled."""
    return workload_config_dir() / name / ENABLED_MARKER_NAME


def workload_is_enabled(name: str) -> bool:
    """Single source of truth for enabled-ness: the marker file is present."""
    return workload_enabled_marker(name).exists()


def iter_workloads(base: Path | None = None) -> list[tuple[str, Path]]:
    """(name, config_path) for every workload under `base`, sorted by name.

    `base` defaults to the config dir (the common case); pass BUNDLES_DIR to
    discover shipped bundles instead. Either way the name is derived from the
    directory so no caller knows the on-disk shape — this is the single place
    discovery encodes the layout.
    """
    if base is None:
        base = workload_config_dir()
    return sorted(
        (p.parent.name, p)                                    # name from dir, not stem
        for p in base.glob("*/workload.toml")
    )


# --- Kind routing ---

def infer_workload_kind(config: dict) -> str:
    """Return 'vm' if the config has a top-level [vm] section, else 'container'."""
    return "vm" if "vm" in config else "container"


# --- virtiofs ---

def virtiofs_tag(container_path: str, index: int = 0) -> str:
    """Derive a virtiofs mount tag (<=36 chars) from a guest mountpoint.

    Single source of truth: the generator, the cloud-init builder, and any
    runtime helpers must derive tags through this function or they will drift.
    """
    tag = container_path.lstrip("/").replace("/", "-") or f"vol{index}"
    tag = re.sub(r'[^a-zA-Z0-9_-]', '-', tag)
    return tag[:36]


def virtiofs_tags(volume_specs) -> list[str]:
    """Collision-free virtiofs tags for a VM's ordered volume list (B3).

    virtiofs_tag() sanitizes then truncates a guest mountpoint to <=36 chars, so
    two distinct mountpoints can collapse to the same tag. The generator keys
    both the virtiofsd sidecar unit filename (workload-<name>-virtiofs-<tag>) and
    the QEMU chardev/device tag off this string, so a collision silently
    overwrites one sidecar unit and emits duplicate chardev tags. Disambiguate
    any colliding tag by suffixing the volume index (kept inside the 36-char
    budget). Order matches the input list.

    Single source of truth: the generator, workload-ensure-user (cloud-init
    mounts), and cmd_lifecycle purge must all derive the tag SET through this so
    unit names / chardev tags / fstab entries stay in sync.
    """
    base = [virtiofs_tag(parse_volume_spec(v)[1], i)
            for i, v in enumerate(volume_specs)]
    counts = {}
    for t in base:
        counts[t] = counts.get(t, 0) + 1
    # Every assigned tag is checked against ALL previously assigned tags, not
    # just the base counts: a suffixed tag ("data" -> "data-1") could otherwise
    # re-collide with another volume's natural un-suffixed tag ("data-1").
    used = set()
    tags = []
    for i, t in enumerate(base):
        cand = t
        bump = i
        while cand in used or (cand == t and counts[t] > 1):
            suffix = f"-{bump}"
            cand = t[:36 - len(suffix)] + suffix
            bump += 1
        used.add(cand)
        tags.append(cand)
    return tags


def parse_volume_spec(vol_spec: str) -> tuple[str, str, str]:
    """Parse a "host:guest[:opts]" volume spec, returning (host, guest, opts).

    A bare token (no ':') is treated as host == guest. opts defaults to "rw".
    Only the first two ':' delimit fields, so opts may itself contain a colon
    (e.g. mount options). This is the single source of truth for the grammar;
    expand_volume_path builds on it.
    """
    parts = vol_spec.split(":", 2)
    host = parts[0]
    guest = parts[1] if len(parts) > 1 else parts[0]
    opts = parts[2] if len(parts) > 2 else "rw"
    return host, guest, opts


# --- Naming conventions ---

def workload_username(name: str) -> str:
    """Return the system username for a workload: _wl-{name}."""
    return f"{USERNAME_PREFIX}{name}"


# Flock guarding the subuid/subgid UID-allocation critical section (#4). Must be
# the identical path across every participant (workload-ensure-user,
# workload-generate, cmd_enable, cmd_disable/purge, cmd_cleanup) or the flock
# stops mutexing. Prefer the remove_/append_subid_entries() helpers below, which
# take the lock themselves, over hand-rolling a read-modify-write here.
SUBID_LOCK = Path("/run/lock/workload-subid.lock")

# Reentrancy state for subid_lock(): the enable path holds the lock across
# allocation *through* the sysusers write, and get_next_uid() (called inside
# that span) now takes the lock too. Nesting on a single cached fd makes the
# inner acquire a no-op instead of a same-process deadlock (a second fd's
# flock() would block against the outer hold). Single-threaded by design —
# both callers (the boot generator, the CLI) run one allocation at a time.
_subid_lock_fd = None
_subid_lock_depth = 0


@contextlib.contextmanager
def subid_lock():
    """Hold SUBID_LOCK for the UID/subid allocation critical section.

    Reentrant within a process (see _subid_lock_depth): only the outermost
    acquire flocks, only the outermost release unlocks. Cross-process this is a
    plain exclusive flock, so a boot-time generate and a concurrent
    `workloadctl enable` can't hand out the same UID.

    Best-effort *only* for a permission failure: if the caller can't open the
    root-owned lock (an unprivileged caller — /run/lock is root-owned) the body
    runs unlocked rather than blocking. Any other OSError (a transient flock
    EINTR, ENOSPC, EIO …) propagates so allocation fails loudly instead of
    silently running without the mutex — the isolation stakes are too high to
    swallow those. Both real callers run as root where the open+flock succeed,
    so the guarantee holds where allocation actually happens; the permission
    escape hatch only keeps the exit-0 boot generator (whose per-workload loop
    already logs-and-continues) from being the thing that trips.
    """
    global _subid_lock_fd, _subid_lock_depth
    if _subid_lock_depth == 0:
        try:
            SUBID_LOCK.parent.mkdir(parents=True, exist_ok=True)
            _subid_lock_fd = open(SUBID_LOCK, "w")
            fcntl.flock(_subid_lock_fd.fileno(), fcntl.LOCK_EX)
        except OSError as e:
            # Drop any half-open fd first (the finally below never runs — we
            # raise before _subid_lock_depth is incremented — so clean up here).
            if _subid_lock_fd is not None:
                _subid_lock_fd.close()
            _subid_lock_fd = None
            # Permission failure → unprivileged caller can't take the root-owned
            # lock; degrade to unlocked. Anything else is a real fault.
            if not isinstance(e, PermissionError):
                raise
    _subid_lock_depth += 1
    try:
        yield
    finally:
        _subid_lock_depth -= 1
        if _subid_lock_depth == 0 and _subid_lock_fd is not None:
            fcntl.flock(_subid_lock_fd.fileno(), fcntl.LOCK_UN)
            _subid_lock_fd.close()
            _subid_lock_fd = None


# The two files the subid lock exists to protect. Named here for the same reason
# every other path this module owns is: so no caller has to spell them, and so
# the read/parse/mutate helpers below are the only implementations of the
# `username:start:count` format.
SUBUID_FILE = Path("/etc/subuid")
SUBGID_FILE = Path("/etc/subgid")


def subuid_file() -> Path:
    """Call-time reader for SUBUID_FILE. Same rationale as
    workload_config_dir(): `from workload_lib import SUBUID_FILE` binds a copy,
    so a single patch.object(workload_lib, "SUBUID_FILE", tmp) would not reach
    it. Callers go through this and are redirected together."""
    return SUBUID_FILE


def subgid_file() -> Path:
    """Call-time reader for SUBGID_FILE. See subuid_file()."""
    return SUBGID_FILE


def subid_files() -> tuple[Path, Path]:
    """Both subid files, resolved at call time."""
    return (subuid_file(), subgid_file())


def read_subid_entry(username: str, path: Path | str) -> tuple[int, int] | None:
    """Return (start, count) for username's main range in path, else None.

    Only the first matching line is considered: the main range is the one
    `username:<start>:<count>` entry: supplementary group entries added by
    extra_groups share the username prefix but are appended after it.
    """
    try:
        with open(path) as f:
            for line in f:
                if line.startswith(f"{username}:"):
                    parts = line.strip().split(":")
                    if len(parts) == 3:
                        try:
                            return int(parts[1]), int(parts[2])
                        except ValueError:
                            return None
    except (FileNotFoundError, PermissionError, OSError):
        return None
    return None


def subid_files_with_entries(username: str) -> list[Path]:
    """Which of the subid files currently carry any entry for username.

    Used by the disable/cleanup dry-run reporting, so it answers "is there
    something to remove" without taking the lock — a stale answer only affects
    a preview line, and remove_subid_entries() re-reads under the lock anyway.
    """
    found = []
    for path in subid_files():
        try:
            text = path.read_text()
        except (FileNotFoundError, PermissionError, OSError):
            continue
        if any(line.startswith(f"{username}:") for line in text.splitlines()):
            found.append(path)
    return found


def replace_file_atomically(
    path: Path | str,
    content: str | bytes,
    *,
    default_mode: int = 0o644,
    owner: tuple[int, int] | None = None,
) -> None:
    """Replace path's whole contents with content, atomically.

    Use this for any file that already holds content worth keeping, whenever a
    reader could observe the write or a crash could outlive it. A plain
    write_text() truncates first, so it has two failure modes: a concurrent
    reader sees a partial file with no way to detect that it is partial, and an
    interrupted write leaves the file permanently truncated — destroying content
    the writer never meant to touch. Writing a sibling temp file and renaming it
    on means readers see either the whole old file or the whole new one, and a
    crash leaves the old one intact.

    Mode and ownership are carried over from the file being replaced, so the
    rename cannot silently reset them; default_mode and owner apply only when
    there is no existing file. The temp lands in path's own directory because
    rename is atomic only within a filesystem.
    """
    path = Path(path)
    tmp = path.with_name("." + path.name + ".tmp")
    try:
        st = path.stat()
        mode, uid, gid = stat.S_IMODE(st.st_mode), st.st_uid, st.st_gid
    except FileNotFoundError:
        mode = default_mode
        uid, gid = owner if owner is not None else (0, 0)
    if owner is not None:
        uid, gid = owner
    body = content.encode() if isinstance(content, str) else content
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode)
    try:
        os.write(fd, body)
        # Durability before the rename: the rename is atomic w.r.t. readers, but
        # without the fsync a crash can land the rename while the data blocks
        # are still unwritten, leaving a zero-length file.
        os.fsync(fd)
    finally:
        os.close(fd)
    os.chmod(tmp, mode)
    try:
        os.chown(tmp, uid, gid)
    except (PermissionError, OSError):
        # Non-root can't chown; the callers that need a specific owner all
        # require root anyway, so losing ownership here would be a bug
        # elsewhere, not a reason to fail the write.
        pass
    os.replace(tmp, path)


def _rewrite_subid_file(path: Path, lines: list[str]) -> None:
    """Replace path's contents with lines, atomically.

    Atomicity is not optional here: podman and newuidmap read /etc/subuid and
    /etc/subgid WITHOUT taking SUBID_LOCK, so cooperating writers alone can't
    make a truncate-then-write safe, and a crash mid-write would lose every
    workload's mapping rather than just the one being removed.
    """
    replace_file_atomically(path, "\n".join(lines) + ("\n" if lines else ""))


def remove_subid_entries(username: str) -> list[Path]:
    """Drop every subuid/subgid entry for username. Returns the files changed.

    Takes SUBID_LOCK itself and holds it across the whole read-filter-write of
    both files, which is what makes this safe to call concurrently with an
    enable that is appending under the same lock. Callers must NOT hand-roll
    this: a read and a write that each take the lock separately is not an
    atomic read-modify-write, and drops a range appended in between.
    """
    changed = []
    with subid_lock():
        for path in subid_files():
            try:
                text = path.read_text()
            except (FileNotFoundError, PermissionError, OSError):
                continue
            kept = [line for line in text.splitlines()
                    if not line.startswith(f"{username}:")]
            if len(kept) != len(text.splitlines()):
                _rewrite_subid_file(path, kept)
                changed.append(path)
    return changed


def append_subid_entries(path: Path | str, entries: list[str]) -> None:
    """Append entries (`username:start:count` strings) to path under the lock.

    Append rather than rewrite on purpose: O_APPEND adds only this workload's
    lines and can never drop another's, so it stays correct even against a
    writer that skipped the lock.
    """
    if not entries:
        return
    with subid_lock():
        with open(path, "a") as f:
            for entry in entries:
                f.write(entry + "\n")


# Per-run tracking set: `get_next_uid` records UIDs allocated during this
# process invocation so multiple workloads enabled in the same run don't race.
_allocated_uids: set[int] = set()


def _reserved_uids_in_pending_sysusers() -> set[int]:
    """UIDs handed out in pending sysusers configs but not yet in /etc/passwd.

    Between allocation and `systemd-sysusers` creating the user, a workload's
    UID lives only in its sysusers .conf: the boot generator writes it into
    /run/systemd/system and defers user creation to the workload's setup
    service (potentially much later), while enable stages a copy in
    /run/sysusers.d. During that gap the UID is invisible to `pwd.getpwall()`,
    so a concurrent allocator would re-hand-out the slot. get_next_uid() unions
    these in — provided every allocator writes its .conf while still holding
    SUBID_LOCK — to close that window. /run is tmpfs (no cross-boot staleness)
    and disable removes the conf, so this set tracks live allocations.
    """
    reserved: set[int] = set()
    for d in (RUN_SYSTEMD_SYSTEM, RUN_SYSUSERS_D):
        try:
            confs = list(d.glob("workload-*.conf"))
        except OSError:
            continue
        for conf in confs:
            try:
                text = conf.read_text()
            except OSError:
                continue
            for line in text.splitlines():
                # sysusers user line: `u <name> <uid|uid:gid> "gecos" <home>`.
                fields = line.split()
                if len(fields) >= 3 and fields[0] == "u":
                    try:
                        reserved.add(int(fields[2].split(":", 1)[0]))
                    except ValueError:
                        pass
    return reserved


def get_next_uid() -> int:
    """Return the next free UID in the workload range [UID_MIN, UID_MAX].

    Combines the live /etc/passwd snapshot with UIDs already allocated in this
    process invocation and UIDs pinned in pending sysusers configs (see
    _reserved_uids_in_pending_sysusers — covers slots handed out but not yet
    created). Takes SUBID_LOCK itself so every caller — including the boot
    generator, which used to allocate unlocked — is mutexed against a concurrent
    allocator picking the same free slot. Reentrant, so the enable path can keep
    the lock held across the subsequent sysusers write.
    """
    with subid_lock():
        used = set(_allocated_uids)
        used |= _reserved_uids_in_pending_sysusers()
        try:
            for pw in pwd.getpwall():
                if UID_MIN <= pw.pw_uid <= UID_MAX:
                    used.add(pw.pw_uid)
        except Exception:
            pass
        for uid in range(UID_MIN, UID_MAX + 1):
            if uid not in used:
                _allocated_uids.add(uid)
                return uid
        raise RuntimeError(f"No free UIDs in range {UID_MIN}-{UID_MAX}")


def workload_service_name(name: str) -> str:
    """Return the systemd service name for a workload."""
    return f"workload-{name}.service"


def workload_container_name(name: str) -> str:
    """Return the podman container name for a workload."""
    return f"workload-{name}"


def workload_podman_container_name(
    name: str, container_name: str, *, is_multi: bool
) -> str:
    """The podman --name for one container of a workload.

    Single source of the single-vs-multi name formula shared by
    WorkloadConfig.podman_container_name and the metrics exporter (which reads
    raw TOML and can't build a WorkloadConfig). Single-container workloads use
    the bare `workload-<name>`; each member of a pod/bridge workload gets
    `workload-<name>-<container>`.
    """
    if not is_multi:
        return workload_container_name(name)
    return f"workload-{name}-{container_name}"


# Generated unit files live in the systemd runtime tree (transient; rewritten on
# boot by workload-generate.service and on every `workloadctl enable`).
RUN_SYSTEMD_SYSTEM = Path("/run/systemd/system")

# Where enable stages a workload's sysusers .conf to apply immediately (the
# generator writes its copy into RUN_SYSTEMD_SYSTEM). Both are scanned by
# _reserved_uids_in_pending_sysusers to spot pinned-but-uncreated UIDs.
RUN_SYSUSERS_D = Path("/run/sysusers.d")

# --- Workload run-files (B15) ---------------------------------------------- #
#
# The single source of truth for "the per-workload files a workload owns" — see
# docs/workload-run-files.md for the authoritative table and rationale.
#
# Every caller slices this one list along whichever axis it cares about, instead
# of re-deriving the set:
#   * emitted view (rf.emitted True) — files that exist for THIS exact config;
#     used by the generator-parity oracle, drift, inspect, and metrics.
#   * removable superset (all kinds but env-file) — the mode-family union the
#     disable/purge path may safely unlink() with missing_ok; over-lists -pod/-net
#     for every container workload so disabling can never miss a topology's unit.
#   * env-tree files (kind == 'env-file') — the runtime-written .env/.secrets that
#     only --purge removes.
# Filter by `kind` for tree/lifecycle and by `role` for a specific unit family.


def workload_env_dir() -> Path:
    """Runtime env tree (.env/.secrets). Honors WORKLOAD_ENV_DIR for tests."""
    return Path(os.environ.get("WORKLOAD_ENV_DIR", "/run/workload-env"))


@dataclass(frozen=True)
class WorkloadRunFile:
    """One file a workload owns, tagged so every caller can filter one list.

    kind  — which tree + removal lifecycle it belongs to:
            'unit' | 'wants-symlink' | 'sysusers' | 'dropin' | 'env-file'.
    role  — which unit family, for callers that want a specific member:
            'main' | 'setup' | 'build' | 'pod' | 'net' | 'container' |
            'virtiofs' | 'sysusers' | 'dropin' | 'env' | 'secrets'.
    emitted — True iff the generator writes this file for THIS config (the
            emitted view). False marks the removable-only superset entries
            (-pod/-net listed for non-matching modes) and the runtime-written
            env-files the generator never produces.
    """

    path: Path
    kind: str
    role: str
    emitted: bool


def workload_run_files(config) -> list[WorkloadRunFile]:
    """The complete set of run-files owned by one workload.

    MUST stay in sync with generators/workload-generate (generate_*_workload) and
    with the removal path. Never includes shared infra (workload-generate.service,
    workload-bridge.service, dnsmasq) or references to *other* workloads' units.

    Superset semantics: -pod.service and -net.service are listed for every
    container workload (emitted only for the matching mode) so the removable view
    can unlink() the full topology with missing_ok. The cgroup drop-in is keyed by
    the workload UID from the passwd db; if the user is gone the UID can't be
    reconstructed, so it is omitted rather than raising.
    """
    # Lazy import: workloadctl_core imports this module, so a top-level import
    # would be circular.
    from workloadctl_core import WorkloadUserNotFound

    run = RUN_SYSTEMD_SYSTEM
    env = workload_env_dir()
    name = config.name
    files: list[WorkloadRunFile] = [
        WorkloadRunFile(run / f"workload-{name}.conf", "sysusers", "sysusers", True),
        WorkloadRunFile(run / f"workload-{name}-setup.service", "unit", "setup", True),
        WorkloadRunFile(run / f"workload-{name}.service", "unit", "main", True),
        WorkloadRunFile(
            run / "multi-user.target.wants" / f"workload-{name}.service",
            "wants-symlink", "main", True,
        ),
    ]

    if config.is_vm:
        files.append(
            WorkloadRunFile(run / f"workload-{name}-build.service", "unit", "build", True)
        )
        for tag in virtiofs_tags(config.config.get("vm", {}).get("volumes", [])):
            files.append(WorkloadRunFile(
                run / f"workload-{name}-virtiofs-{tag}.service", "unit", "virtiofs", True
            ))
    else:
        # cgroup-placement drop-in (containers only). Keyed by the workload UID
        # from the passwd db; omitted once the user is gone (UID unreconstructable).
        # A pure query helper must not allocate a UID.
        try:
            files.append(WorkloadRunFile(
                run / f"user@{config.uid}.service.d" / "50-workload.conf",
                "dropin", "dropin", True,
            ))
        except WorkloadUserNotFound:
            pass
        mode = config.mode
        files.append(WorkloadRunFile(
            run / f"workload-{name}-pod.service", "unit", "pod", mode == "pod"
        ))
        files.append(WorkloadRunFile(
            run / f"workload-{name}-net.service", "unit", "net", mode == "bridge"
        ))
        # Per-container units key on topology, matching the generator and the
        # -pod/-net gates above; the per-container .secrets below key on the same
        # `mode != "single"` so disable/purge lists units and secrets together.
        if mode != "single":
            for cname in config.container_names():
                files.append(WorkloadRunFile(
                    run / f"workload-{name}-{cname}.service", "unit", "container", True
                ))

    # Runtime-written env tree — never produced by the generator (emitted False),
    # removed only on --purge. .secrets is over-listed per container (missing_ok).
    files.append(WorkloadRunFile(env / f"workload-{name}.env", "env-file", "env", False))
    files.append(
        WorkloadRunFile(env / f"workload-{name}.secrets", "env-file", "secrets", False)
    )
    # Per-container .secrets gate on the SAME discriminator as the per-container
    # units above (mode != "single"), not is_multi — a split discriminator here
    # strands loaded units when the two disagree (cmd_disable would unlink these
    # .secrets but never list the matching .service units). Correctly False for
    # VMs too (mode "single"; they own no per-container secrets).
    if config.mode != "single":
        for cname in config.container_names():
            files.append(WorkloadRunFile(
                env / f"workload-{name}-{cname}.secrets", "env-file", "secrets", False
            ))

    return files


@dataclass(frozen=True)
class RunTreeScan:
    """How to find one run-file kind when scanning the whole run tree.

    Companion to workload_run_files(): that lists the files ONE config owns;
    this lists the glob per kind so a tree-walker (workloadctl drift) can compare
    generated-vs-live for every workload at once, in both directions, without
    re-deriving the workload-<name>* name formulas. Kinds mirror
    WorkloadRunFile.kind for the files that land under RUN_SYSTEMD_SYSTEM — the
    env-file kinds live in the env tree and never appear here.

    glob          — pattern under the run root (drift's scratch dir or the live
                    tree); may descend a subdir (wants/, user@*.service.d/).
    content       — True: drift is a byte diff of the file. False: the file is an
                    enablement symlink whose only drift is presence/absence.
    name_filtered — True: the file is named workload-<name>* so `drift <name>`
                    can scope to it. False: drop-ins are keyed by UID, so the
                    name filter can't apply and they are always in scope.
    """

    kind: str
    glob: str
    content: bool
    name_filtered: bool


# Every run-file kind that lands under RUN_SYSTEMD_SYSTEM, as a scan table for
# drift. Adding a kind here (alongside its workload_run_files entry) is all drift
# needs to start comparing it — there is no per-kind block to duplicate.
# test_run_tree_scans_cover_run_files pins this to workload_run_files' tree kinds.
RUN_TREE_SCANS: list[RunTreeScan] = [
    RunTreeScan("unit", "workload-*.service", content=True, name_filtered=True),
    RunTreeScan("sysusers", "workload-*.conf", content=True, name_filtered=True),
    RunTreeScan(
        "wants-symlink",
        "multi-user.target.wants/workload-*.service",
        content=False,
        name_filtered=True,
    ),
    RunTreeScan(
        "dropin",
        "user@*.service.d/50-workload.conf",
        content=True,
        name_filtered=False,
    ),
]


def workload_service_units(config, *, roles=None) -> list[str]:
    """Emitted systemd .service unit names for THIS config.

    A convenience view over workload_run_files(): the services the generator
    actually writes — main, setup, the matching pod/net helper or per-container
    services, and for VMs the build and virtiofs units. Pass roles to keep only
    a subset, e.g. roles={"setup", "build"} for a VM's gating units.
    """
    return [
        rf.path.name
        for rf in workload_run_files(config)
        if rf.kind == "unit" and rf.emitted and (roles is None or rf.role in roles)
    ]


def render_sysusers_config(
    *,
    name: str,
    user_name: str,
    uid: int,
    home_dir: str,
    extra_groups=(),
    is_vm: bool = False,
) -> str:
    """Render the systemd-sysusers config for a workload's dedicated user.

    The generator is the sole producer of this .conf: both boot and enable-time
    provisioning go through it (enable consumes the generator's output rather
    than re-rendering — see cmd_lifecycle._generate_units / _provision_user), so
    there is one producer and nothing to drift. UID must be pre-allocated by the
    caller — this is a pure render and never allocates. A VM gets implicit `kvm`
    membership, de-duplicated against extra_groups so it is never emitted twice.
    """
    lines = [
        f"# Workload user for {name}" + (" (VM)" if is_vm else ""),
        f'u {user_name} {uid} "{name} workload" {home_dir}',
    ]
    groups: list[str] = []
    if is_vm:
        groups.append("kvm")
    for group in extra_groups:
        if group not in groups:
            groups.append(group)
    for group in groups:
        lines.append(f"m {user_name} {group}")
    return "\n".join(lines) + "\n"


def units_outdated(name: str) -> bool:
    """True if the workload's config TOML is newer than its generated unit file.

    `systemctl daemon-reload` re-runs the *shell* generator only (which emits a
    boot oneshot), NOT the Python unit-writer — so editing a workload.toml does
    not regenerate the per-workload units until `workloadctl enable <name>` is
    re-run. This mtime comparison is the cheap heads-up for that foot-gun; the
    authoritative content-level check is `workloadctl drift`.

    Returns False if either file is absent (workload never enabled / no config)
    so callers can treat "can't tell" as "nothing to warn about". A 1s slack
    swallows same-second writes from an enable that wrote both.
    """
    try:
        unit_mtime = (RUN_SYSTEMD_SYSTEM / workload_service_name(name)).stat().st_mtime
        config_mtime = workload_config_path(name).stat().st_mtime
    except OSError:
        return False
    return config_mtime > unit_mtime + 1.0


# What unit_generator_version() reports for a unit that carries the provenance
# comment without a version — i.e. one written by a workloadctl older than the
# stamp itself. Truthy, because that is a real "regenerate me" condition and the
# most likely one to be seen in the field exactly once per host.
UNSTAMPED_BUILD = "an unstamped build (pre-versioned units)"


def unit_generator_version(path: Path | str) -> str | None:
    """The workloadctl build that generated the unit file at `path`.

    Returns UNSTAMPED_BUILD when the file carries the provenance comment with no
    version, and None when the file is absent, unreadable, or was not written by
    the generator at all — callers treat None as "nothing to say".

    Only the head of the file is scanned: the stamp lives in the preamble, and a
    generated unit is a few KiB at most.
    """
    try:
        with open(path, "r") as f:
            head = f.read(2048)
    except OSError:
        return None
    match = GENERATED_BY_RE.search(head)
    if match is None:
        return None
    return match.group(1) or UNSTAMPED_BUILD


def units_from_other_build(name: str) -> str | None:
    """The build that generated this workload's live main unit, if not ours.

    The companion to units_outdated(): that one catches "the TOML moved under the
    units", this one catches "the software moved under the units". They are
    independent — an RPM upgrade changes neither file's mtime, and a TOML edit
    does not change the stamp — so both are needed, and the remedy for both is
    the same `workloadctl enable`.

    Returns None when the stamps agree, when the unit does not exist, or when the
    unit predates the generator writing one.
    """
    stamped = unit_generator_version(RUN_SYSTEMD_SYSTEM / workload_service_name(name))
    if stamped is None or stamped == WORKLOADCTL_VERSION:
        return None
    return stamped


STATE_SUBDIR = "state"
DATA_SUBDIR = "data"


def workload_root_dir(name: str) -> Path:
    """Per-workload durable-state root: /var/lib/workloads/<name>.

    Spans both the reconstructible state/ subtree and the precious data/ subtree;
    use this for writable-path grants and containment checks.
    """
    return WORKLOADS_BASE / name


def workload_state_dir(name: str) -> Path:
    """Reconstructible state subtree (= $HOME / podman graphroot / VM disks).

    Backup-skipped (rebuildable from registries/Containerfiles).
    """
    return WORKLOADS_BASE / name / STATE_SUBDIR


def workload_data_dir(name: str) -> Path:
    """Precious data subtree. './' volume anchors resolve here. Backup-captured."""
    return WORKLOADS_BASE / name / DATA_SUBDIR


def workload_home_dir(name: str) -> Path:
    """Workload $HOME — the state/ subdir (podman graphroot lives here)."""
    return workload_state_dir(name)


# Per-container keys that may appear at *either* nesting depth in a
# [[containers]] entry:
#   [containers.container.environment] / [containers.container.health]   (nested)
#   [containers.environment]           / [containers.health]              (sibling)
# Single-mode TOMLs always nest these under [container], so we normalize the
# multi-container form to match. The generator reads from container["container"]
# only, so callers do not need to care which form the TOML used.
_LIFTED_CONTAINER_KEYS = ("environment", "health")


def normalize_containers(config: dict) -> list[dict]:
    """Return a list of per-container config dicts in a single canonical shape.

    Single-container TOMLs (top-level [container] block plus top-level
    [security], [storage], [devices], [secrets], [resources]) become a
    one-element list with all per-container fields gathered into it.

    Multi-container TOMLs ([[containers]] arrays) keep their per-entry
    structure, but sibling [containers.environment] / [containers.health]
    are lifted into entry["container"]["environment"] / ["health"] so the
    generator and helpers see the same shape regardless of which TOML form
    the user wrote.
    """
    if "containers" in config:
        result = []
        for entry in config["containers"]:
            normalized = dict(entry)
            container = dict(normalized.get("container", {}))
            for key in _LIFTED_CONTAINER_KEYS:
                if key in normalized:
                    container[key] = normalized.pop(key)
            normalized["container"] = container
            result.append(normalized)
        return result

    container = {
        "name": config["workload"]["name"],
        "container": dict(config.get("container", {})),
        "security": dict(config.get("security", {})),
        "storage":  {"volumes": list(config.get("storage", {}).get("volumes", []))},
        "devices":  dict(config.get("devices", {})),
        "secrets":  dict(config.get("secrets", {})),
        "resources": dict(config.get("resources", {})),
    }
    return [container]


# --- Validation ---

def infer_workload_mode(config: dict) -> str:
    """Return 'single', 'pod', or 'bridge'. Validates the value if explicit."""
    mode = config.get("workload", {}).get("mode")
    if mode is not None:
        if mode not in VALID_WORKLOAD_MODES:
            raise ValueError(
                f"Invalid workload.mode {mode!r}; must be one of {VALID_WORKLOAD_MODES}"
            )
        return mode
    return "pod" if "containers" in config else "single"


# --- Per-workload SELinux identifiers ---
#
# Each workload that ships extra rights gets its own name-keyed type instead of
# widening the shared container_t: a CIL module `wl_<name>` defining the process
# domain `wl_<name>.process`. The CLI (which loads the policy) and the generator
# (which labels the container) both derive identifiers through these functions
# so they can't drift. See llms.txt "SELinux confinement" for the rationale.
#
# hyphen->underscore is injective: NAME_PATTERN forbids underscores, so two
# distinct workload names can never collide on the same type.

def selinux_module_name(name: str) -> str:
    """SELinux/CIL module (block) name for a workload, e.g. 'wl_wayfire_bob'."""
    return "wl_" + name.replace("-", "_")


def selinux_type_name(name: str) -> str:
    """SELinux process type for a workload, e.g. 'wl_wayfire_bob.process'.

    Passed to `podman --security-opt label=type:`.
    """
    return selinux_module_name(name) + ".process"


# --- Volume path expansion ---

def _safe_anchor_subpath(sub: str) -> str:
    """Reject traversal/absolute escapes from a workload-relative anchor."""
    if sub.startswith("/") or ".." in Path(sub).parts:
        raise ValueError(f"unsafe anchored volume subpath: {sub!r}")
    return sub


def _expand_anchor(host: str, home_dir: str) -> str:
    """Resolve a workload-relative volume anchor to an absolute host path.

    home_dir is the workload STATE dir (= $HOME). The DATA dir is its sibling.
      data/sub  (sugar ./sub)  -> <root>/data/sub        (precious)
      state/sub (sugar @/sub)  -> <root>/state/volumes/sub (reconstructible)
    Anything else is returned unchanged.
    """
    data_root = str(Path(home_dir).parent / DATA_SUBDIR)
    state_vol_root = home_dir + "/volumes"
    # ./ and @/ are sugar for the canonical data/ and state/ prefixes. An empty
    # subpath (e.g. "./" or bare "data") resolves to the anchor root itself.
    for prefix, root in (("./", data_root), ("@/", state_vol_root),
                         ("data/", data_root), ("state/", state_vol_root)):
        if host.startswith(prefix):
            sub = _safe_anchor_subpath(host[len(prefix):])
            return root + "/" + sub if sub else root
    if host == "data":
        return data_root
    if host == "state":
        return state_vol_root
    return host


def expand_volume_path(vol_spec: str, home_dir: str) -> str:
    """Expand a workload-relative anchor in a volume spec's host path.

    Args:
        vol_spec: "host:guest[:opts]" — host may use ./ @/ data/ state/ anchors.
        home_dir: the workload STATE dir (= $HOME); data/ is its sibling.

    Returns the spec with the host path made absolute, original arity preserved.
    """
    host, guest, opts = parse_volume_spec(vol_spec)
    host = _expand_anchor(host, home_dir)
    ncolons = vol_spec.count(':')
    if ncolons == 0:
        return host
    if ncolons == 1:
        return f"{host}:{guest}"
    return f"{host}:{guest}:{opts}"


# --- Instance token expansion ---

# ${WORKLOAD_*} tokens usable in workload.toml values that must name the
# instance. Deliberately the same vocabulary provisioning.host_setup_env()
# exports to [host] setup scripts, so a bundle spells its own identity one way
# whether it's doing so from TOML or from shell.
WORKLOAD_TOKEN_PATTERN = re.compile(r'\$\{(WORKLOAD_[A-Z_]+)\}')


def workload_tokens(name: str) -> dict:
    """The ${WORKLOAD_*} token table for one instance."""
    return {
        "WORKLOAD_NAME": name,
        "WORKLOAD_INSTANCE_DIR": str(workload_config_dir() / name),
        "WORKLOAD_ROOT_DIR": str(workload_root_dir(name)),
        "WORKLOAD_STATE_DIR": str(workload_state_dir(name)),
        "WORKLOAD_DATA_DIR": str(workload_data_dir(name)),
    }


# Derived from the table itself so the two can't drift; the instance name is
# irrelevant to the key set.
WORKLOAD_TOKEN_NAMES = frozenset(workload_tokens("_"))


def expand_workload_tokens(value: str, name: str) -> str:
    """Expand ${WORKLOAD_*} tokens in a config value against instance `name`.

    Exists because a bundle can be instantiated under a different name
    (`init --as`), so any absolute path a TOML hardcodes for *itself* is wrong
    for every instance but the first. The alternative — writing
    /etc/workloads.d/<bundle>/... literally — silently points at a workload
    that doesn't exist.

    Unknown WORKLOAD_ tokens raise: a typo left to pass through would reach
    podman verbatim as a path that can never resolve, and failing at generate
    time with the token named is far easier to diagnose than a container that
    won't start.
    """
    tokens = workload_tokens(name)

    def sub(m):
        key = m.group(1)
        if key not in tokens:
            raise ValueError(
                f"unknown token ${{{key}}} (known: {', '.join(sorted(tokens))})")
        return tokens[key]

    return WORKLOAD_TOKEN_PATTERN.sub(sub, value)


# --- Quoting ---

def dq(s: str) -> str:
    """Quote a string as a LITERAL token for a systemd Exec* command line.

    Use for all tokens: paths, image names, command args, container names, env
    keys, and plain env VALUES.

    systemd applies two expansions to Exec directives that shell-style quoting
    does NOT suppress, so a bare double-quote is not enough:

      * `%` specifiers (`%i`, `%H`, …) are expanded at unit load, before quote
        parsing — a literal `%` must be written `%%`.
      * `$VAR` / `${VAR}` environment expansion runs on each argument *after*
        the command line is split and quotes are removed — so neither single nor
        double quotes stop it; a literal `$` must be written `$$`.

    (This is why single-quoting env values with shlex.quote was wrong: systemd
    still expands `$` inside them, and shlex's `'"'"'` escaping for an embedded
    single quote is shell syntax, not systemd's.)

    Backslash and double-quote are escaped for the surrounding double quotes;
    `$` and `%` are doubled to defeat the two expansions above. A single quote
    needs no escaping inside double quotes.
    """
    return (
        '"'
        + s.replace('\\', '\\\\')
           .replace('"', '\\"')
           .replace('$', '$$')
           .replace('%', '%%')
        + '"'
    )


def uq(s: str) -> str:
    """Quote a string as a LITERAL value for a NON-Exec systemd unit setting
    (RequiresMountsFor=, ReadWritePaths=, ...).

    Differs from dq() in exactly one way, and the difference matters: `$` /
    `${VAR}` expansion runs only on Exec command lines, so a `$` in an ordinary
    setting is *already* literal and doubling it would corrupt the value. `%`
    specifiers are expanded at unit load for every setting, so a literal `%`
    still has to be written `%%`.
    """
    return (
        '"'
        + s.replace('\\', '\\\\')
           .replace('"', '\\"')
           .replace('%', '%%')
        + '"'
    )
