#!/bin/bash
# Host setup for the caddy workload.
#
# Usage:
#   setup.sh enable   — generate the Caddy PKI snippet for this host
#   setup.sh disable  — no-op (nothing host-global to remove)
#
# The Caddyfile imports /etc/caddy/pki/*.caddyfile. This script writes that
# snippet based on whether the shared Homelab CA *private key* has been placed
# on this host, so Caddy either roots its internal `local` CA at the shared
# homelab root (key present) or falls back to its own auto-generated internal
# CA (key absent) — keeping caddy running instead of crash-looping on a missing
# key file. Idempotent. Called by workloadctl enable/disable.
set -euo pipefail

WORKLOAD_NAME="caddy"
DATA_DIR="/var/lib/workloads/${WORKLOAD_NAME}/data"
PKI_DIR="${DATA_DIR}/pki"
CA_KEY="${DATA_DIR}/homelab-root.key"
SNIPPET="${PKI_DIR}/homelab-ca.caddyfile"

enable() {
    mkdir -p "$PKI_DIR"

    # Regular file AND non-empty: an empty placeholder (written below on a prior
    # keyless enable) or a stray directory (left by workload-ensure-user) must
    # NOT count as a real key. `-s` alone is true for a directory.
    if [ -f "$CA_KEY" ] && [ -s "$CA_KEY" ]; then
        echo "  [host] Homelab CA key found — Caddy will mint under the shared root."
        cat > "$SNIPPET" <<'SNIP'
# Shared Homelab CA — generated by setup.sh because the CA key is present.
# Roots Caddy's internal `local` CA at the shared homelab root so every host's
# *.local leaf chains to the one root clients already trust.
pki {
    ca local {
        name "Homelab"
        root {
            cert /etc/caddy/homelab-root.crt
            key  /etc/caddy/homelab-root.key
        }
    }
}
SNIP
    else
        echo "  [host] Homelab CA key not found (or empty) at $CA_KEY."
        echo "         Caddy will use its OWN internal CA (per-host self-signed root)."
        echo "         Sites still serve HTTPS, but clients won't trust them until you"
        echo "         set up the shared CA. To enable it: place the 0400 key at"
        echo "         $CA_KEY (see README 'Shared homelab CA'), then re-run:"
        echo "           sudo workloadctl disable caddy && sudo workloadctl enable caddy"

        # The ./homelab-root.key bind-mount source must be a regular file, or
        # workload-ensure-user creates a *directory* there at service start —
        # which later blocks `install`-ing the real key and confuses the mount.
        # An empty placeholder is harmless: the comment-only snippet below does
        # not reference it. Clear a stale directory left by an older enable.
        if [ -e "$CA_KEY" ] && [ ! -f "$CA_KEY" ]; then
            rm -rf "$CA_KEY"
        fi
        [ -e "$CA_KEY" ] || : > "$CA_KEY"

        cat > "$SNIPPET" <<'SNIP'
# Homelab CA key not present on this host: no shared-root override.
# Caddy's `local_certs` falls back to its own auto-generated internal CA.
SNIP
    fi

    # Root-owned, world-readable: the keep-id container reads it the same way it
    # reads the root-owned ./homelab-root.crt. (Can't chown to the workload user
    # here — on first enable that user isn't provisioned until after this hook.)
    chmod 0644 "$SNIPPET"
}

disable() {
    # The snippet is regenerated on the next enable and is inert while the
    # container is stopped; nothing host-global to tear down.
    :
}

case "${1:-}" in
    enable)  enable ;;
    disable) disable ;;
    *)
        echo "Usage: $0 {enable|disable}" >&2
        exit 1
        ;;
esac
