#!/usr/bin/env python3
"""Render every DEPLOYED workload config through two generator trees and diff
the emitted units byte-for-byte.

WHY THIS EXISTS

A phase that adds an opt-in feature owes one guarantee above all others: a
workload that does not opt in gets *exactly* what it got before. The in-tree
snapshot fixtures (`tests/test_generator_snapshot.py`) assert that against
bundles committed to this repo -- which is the smaller set, and the one whose
shapes were chosen by whoever wrote the feature. A `[network]` shape that no
bundle contains but a live host does is precisely what a bundle-derived
snapshot is structurally unable to cover, and "no shipped bundle uses that
combination" is a claim about this repository, not about anybody's hosts.

So this rig reads the other set: `/etc/workloads.d` on real hosts. It renders
each config through the generator from two git revisions and diffs every
emitted unit and sysusers file.

WHAT IT NEEDS

  - ssh (BatchMode) to each host, and passwordless sudo there to read
    /etc/workloads.d
  - a git checkout of this repo; the two revisions are materialised with
    `git archive`, so neither the worktree nor the current branch is touched

No root here, no KVM, no podman: the generator is a pure function from config
to unit text, which is the whole reason this check is cheap enough to run
against every host every time.

    ./deployed_snapshot_rig.py --before <rev> [--after <rev>] <host> [host...]
    ./deployed_snapshot_rig.py --before main --self-check <host>

`--self-check` perturbs the "after" generator and re-runs, asserting every row
goes red. A differ that cannot detect a difference reports 100% identical for
the same reason a broken one does.

TWO THINGS THAT MADE IT LIE, BOTH FIXED HERE

  - The render root is a fresh mkdtemp per invocation and its path is embedded
    in emitted `ExecStart=` lines, so every unit differed for a reason having
    nothing to do with the generator. Scrubbed.
  - A workload that is *disabled* on its host carries no `.enabled` marker, so
    the generator skips it and it renders zero units on both sides -- which
    compares equal and proves nothing. The marker is forced (the guarantee is
    about the config shape, and a disabled workload can be re-enabled at any
    time) and a zero-unit render is a hard error.
"""
import argparse
import difflib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# The generator stamps its own provenance into each unit; that line is expected
# to differ between revisions and is not a behaviour change.
STAMP = re.compile(r"^#\s*(Generated by|Auto-generated).*$", re.M)

# Any of these keys at top level means the workload OPTED IN to egress
# inspection, so its units are *supposed* to change. Reported, never asserted.
TRIGGERS = re.compile(
    r"^\s*(hosts|policy|allow|internal|splice|tls|ca_delivery|egress)\s*=", re.M)

# Keys that, combined with mode = "host", validate_container_network() now
# refuses outright (P0-1): under host mode the container's sockets ARE host
# sockets, so two of three in-container uid arms leave as subuids no shipped
# single-uid rule matches.
HOST_MODE = re.compile(r'^\s*mode\s*=\s*"host"', re.M)
EGRESS_KEYS = ("hosts", "policy", "allow", "internal", "splice", "tls",
               "ca_delivery")

results = []


def record(label, ok, detail=""):
    results.append(ok)
    print(f"  {'PASS' if ok else 'FAIL'}  {label}" + (f"  -- {detail}" if detail else ""))


def fetch(host, dest):
    """Pull /etc/workloads.d off a host. Returns the number of configs found."""
    dest.mkdir(parents=True, exist_ok=True)
    tar = subprocess.run(
        ["ssh", "-o", "BatchMode=yes", host,
         "cd /etc/workloads.d && sudo tar cf - $(ls)"],
        capture_output=True)
    if tar.returncode != 0:
        print(f"  ssh {host} failed: {tar.stderr.decode()[:200]}")
        return 0
    subprocess.run(["tar", "xf", "-", "-C", str(dest)], input=tar.stdout, check=True)
    return len(list(dest.glob("*/workload.toml")))


def materialise(rev, dest):
    """git archive a revision's workloadctl/ tree. Leaves the worktree alone."""
    dest.mkdir(parents=True, exist_ok=True)
    # git pathspecs are relative to the cwd, and this rig is normally run from
    # workloadctl/ -- where "workloadctl" names nothing.
    top = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                         capture_output=True, text=True, check=True).stdout.strip()
    archive = subprocess.run(["git", "archive", rev, "workloadctl"],
                             cwd=top, capture_output=True, check=True)
    subprocess.run(["tar", "x", "-C", str(dest)], input=archive.stdout, check=True)
    return dest / "workloadctl"


def render(tree, cfgsrc):
    """Run the generator from `tree` over one workload dir; return its units."""
    out = Path(tempfile.mkdtemp())
    cfg, svc, sysusers = out / "cfg", out / "svc", out / "sysusers"
    for d in (cfg, svc, sysusers):
        d.mkdir()
    shutil.copytree(cfgsrc, cfg / cfgsrc.name)
    (cfg / cfgsrc.name / ".enabled").touch()

    env = dict(os.environ,
               WORKLOAD_CONFIG_DIR=str(cfg), SYSUSERS_DIR=str(sysusers),
               PYTHONPATH=str(tree / "lib"), PYTHONHASHSEED="0",
               WORKLOAD_GENERATE_LOG_STDERR="1")
    proc = subprocess.run(
        [sys.executable, str(tree / "generators" / "workload-generate"), str(svc)],
        capture_output=True, text=True, env=env)

    def scrub(text):
        return STAMP.sub("# <stamp>", text.replace(str(out), "<root>"))

    units = {}
    for base, prefix in ((svc, ""), (sysusers, "sysusers/")):
        for f in sorted(base.rglob("*")):
            if f.is_file():
                units[prefix + str(f.relative_to(base))] = scrub(f.read_text())
    shutil.rmtree(out, ignore_errors=True)
    return units, proc.returncode, scrub(proc.stderr)


def compare(before_tree, after_tree, configs, verbose=True):
    """Diff every config across the two trees. Returns the number that differ."""
    differing = 0
    for toml in configs:
        wl = toml.parent
        label = f"{wl.parts[-2]}/{wl.name}"
        b, brc, _ = render(before_tree, wl)
        a, arc, aerr = render(after_tree, wl)
        trig = TRIGGERS.search(toml.read_text())
        tag = f"opted in via `{trig.group(1)}`" if trig else "no trigger"

        if not a:
            if verbose:
                record(f"{label} renders units at all", False,
                       f"zero units emitted -- identical would prove "
                       f"nothing: {aerr.strip()[:200]}")
            differing += 1
            continue
        if b == a and brc == arc:
            if verbose:
                record(f"{label} is byte-identical", True, f"{len(a)} units, {tag}")
            continue

        differing += 1
        if verbose:
            record(f"{label} is byte-identical", False, tag)
            for k in sorted(set(b) | set(a)):
                if b.get(k) != a.get(k):
                    print(f"        unit {k}:")
                    for line in list(difflib.unified_diff(
                            b.get(k, "").splitlines(), a.get(k, "").splitlines(),
                            "before", "after", lineterm=""))[:40]:
                        print("          " + line)
    return differing


def self_check(before_tree, after_tree, configs):
    """Perturb the "after" generator and confirm EVERY row goes red.

    Without this the rig's headline number is unfalsifiable: a differ that
    compares nothing prints the same "all identical" as one that works. The
    mutation is a directive added to the setup service every workload gets, so
    the correct answer is "all of them", not "most of them".
    """
    # The setup service is rendered wherever the generator keeps it -- it has
    # lived in the entrypoint and in lib/gen_common.py -- so the anchor is
    # located by content, not by path. A path would read "anchor missing" for
    # a move, which is the same verdict as a real deletion.
    anchor = 'svc.set("RemainAfterExit", "yes")'
    context = "systemd-sysusers"
    gen = None
    for cand in (after_tree / "lib" / "gen_common.py",
                 after_tree / "generators" / "workload-generate"):
        if cand.exists() and anchor in cand.read_text() and context in cand.read_text():
            gen = cand
            break
    if gen is None:
        record("self-check: the mutation anchor still exists", False,
               f"{anchor!r} beside {context!r} found in no candidate file -- "
               "the rig cannot verify itself")
        return
    original = gen.read_text()
    # Re-indent to the anchor's own column. A probe pasted at column 0 is an
    # IndentationError, and the generator then emits nothing at all -- which
    # this rig would report as 18 broken configs rather than as a rig bug.
    mutated = re.sub(r"^([ \t]*)" + re.escape(anchor) + r"$",
                     lambda m: f"{m.group(0)}\n{m.group(1)}"
                               'svc.set("X-Mutation-Probe", "1")',
                     original, flags=re.M)
    if mutated == original:
        record("self-check: the mutation applied", False,
               "anchor present but no line matched -- indentation regex is stale")
        return
    gen.write_text(mutated)
    try:
        differing = compare(before_tree, after_tree, configs, verbose=False)
        record("self-check: a mutated generator makes every row differ",
               differing == len(configs), f"{differing}/{len(configs)} went red")
    finally:
        gen.write_text(original)
        record("self-check: reverting the mutation restores agreement",
               compare(before_tree, after_tree, configs, verbose=False) == 0,
               "a mutation left behind would make the next run lie")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("hosts", nargs="+", help="ssh targets running workloadctl")
    ap.add_argument("--before", required=True, help="revision the phase started from")
    ap.add_argument("--after", default="HEAD", help="revision to compare against")
    ap.add_argument("--self-check", action="store_true",
                    help="also prove the differ can see a difference")
    args = ap.parse_args()

    root = Path(tempfile.mkdtemp(prefix="deployed-snapshot-"))
    print(f"scratch: {root}\n")
    try:
        print("== collecting deployed configs ==")
        for host in args.hosts:
            n = fetch(host, root / "deployed" / host.replace("@", "_"))
            record(f"read /etc/workloads.d from a host", n > 0, f"{n} configs")

        configs = sorted((root / "deployed").glob("*/*/workload.toml"))
        if not configs:
            print("\nno configs collected; nothing to compare")
            return 1

        before_tree = materialise(args.before, root / "before")
        after_tree = materialise(args.after, root / "after")

        print(f"\n== {len(configs)} configs, {args.before} -> {args.after} ==")
        differing = compare(before_tree, after_tree, configs)

        print("\n== the mode = \"host\" refusal against live configs ==")
        # "No shipped bundle uses that combination" was a claim about this
        # repository. A deployed config that pairs host mode with an egress key
        # would now FAIL VALIDATION, and the generator emits no units for it --
        # so the workload stops running rather than running unfiltered. That
        # fails closed, which is right, but it is still an outage, and the only
        # place to find out is here.
        host_mode = [t for t in configs if HOST_MODE.search(t.read_text())]
        broken = []
        for toml in host_mode:
            text = toml.read_text()
            named = [k for k in EGRESS_KEYS
                     if re.search(rf"^\s*{k}\s*=", text, re.M)]
            if named:
                broken.append(f"{toml.parent.parts[-2]}/{toml.parent.name}: {named}")
        record("no deployed host-mode workload pairs it with an egress key",
               not broken,
               "; ".join(broken) if broken
               else f"{len(host_mode)} deployed workloads use mode = \"host\", "
                    f"none with an egress key")

        if args.self_check:
            print("\n== self-check ==")
            self_check(before_tree, after_tree, configs)

        passed = sum(1 for r in results if r)
        print(f"\n{passed}/{len(results)} assertions passed")
        return 0 if passed == len(results) else 1
    finally:
        shutil.rmtree(root, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
