#!/usr/bin/env python3
"""inspect_rig.py — does a guest with no proxy variables actually land in the
transparent egress inspector, and does the proxy path survive it?

Run this ON a KVM host with the workloadctl RPM installed. It boots two
throwaway VM workloads and probes them from inside.

WHY TWO GUESTS

Rung 1's claim has two halves that fail independently, and a single guest
proves neither on its own:

  plain  filtered, no `hosts`   the guest has NO proxy variables. Its dial to
                                80/443 is DNAT'd onto the listener. This is
                                the rung's headline claim.
  proxy  filtered, with `hosts` the guest has tinyproxy. Its upstream CONNECT
                                leg is tcp dport 443 from the same uid, so
                                without the wl_inspect_cg exemption it would be
                                redirected into the listener it was dialling
                                past, and every proxied HTTPS request would
                                fail. That
                                exemption has no unit test that can see it fail
                                -- it is a cgroup id resolved at add time.

The two differ in exactly one config line, which is what makes a failure
attributable.

WHAT ONLY A REAL BOOT CAN SHOW

The inspect socket is ordered after workload-<name>-setup.service, which is
what creates _wl-<name>. The generator computes the listener address from that
user's uid, so a socket that starts before setup fails to resolve the user and
takes the VM down with it. Every unit test passes with that ordering missing.
"""

import argparse
import json
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path

BASE_IMAGE = Path("/var/lib/broker-rig/base.qcow2")
DNS_ALLOW = "1.1.1.1:53"
PROXY_HOST = "example.com"

# Spelled out rather than imported from lib/vm.py: a rig that computes both
# sides from one constant cannot notice them drifting apart.
PORT_CLEARTEXT = 8080
PORT_TLS = 8443
ORIG_CLEARTEXT = 80
ORIG_TLS = 443

# A v4 literal that is routable-looking but never dialled for real: the whole
# point is that the packet is translated before it leaves the host, so what is
# on the far side is irrelevant. Using a literal keeps DNS out of the probe.
PROBE_V4 = "93.184.216.34"
PROBE_V6 = "2606:2800:220:1:248:1893:25c8:1946"
# The /48 the v6 probe lives in. A host with no IPv6 uplink has no route to it,
# and a connect() with no route fails at the routing lookup -- BEFORE the nat
# output hook runs, so the redirect never gets the chance to act and the probe
# reports a v6 failure that says nothing about the redirect. The rig installs
# this route on the dummy link for the duration of the v6 probes so that the
# question under test is the redirect and not the host's uplink. It is removed
# again; a host that already routes the prefix is left alone.
PROBE_V6_NET = "2606:2800:220::/48"
INSPECT_LINK = "workload-proxy"


@dataclass(frozen=True)
class Arm:
    name: str
    proxy: bool


ARMS = (Arm("wlri-plain", False), Arm("wlri-proxy", True))

results = []


def say(msg):
    print(msg, flush=True)


def record(label, ok, detail):
    results.append((label, ok, detail))
    say(f"  {'PASS' if ok else 'FAIL'}  {label}: {detail}")


def run(argv, check=True, timeout=120):
    p = subprocess.run(argv, capture_output=True, text=True, timeout=timeout)
    if check and p.returncode != 0:
        raise RuntimeError(f"{argv!r} rc={p.returncode}\n{p.stdout}\n{p.stderr}")
    return p


def guest(name, script, timeout=90):
    """A bash login shell, so profile.d applies as well as PAM's
    /etc/environment -- the two places the guest env is written."""
    return subprocess.run(
        ["workloadctl", "exec", name, "--", "bash", "-lc", script],
        capture_output=True, text=True, timeout=timeout)


def preflight():
    if Path("/proc/self/uid_map").read_text().split()[1] != "0":
        sys.exit("run as root")
    for p in (BASE_IMAGE, Path("/usr/libexec/workloadctl/workload-vm-inspect"),
              Path("/usr/libexec/workloadctl/workload-vm-inspect-listener")):
        if not p.exists():
            sys.exit(f"missing {p}")
    if not Path("/dev/kvm").exists():
        sys.exit("no /dev/kvm")


def toml_for(arm):
    lines = [
        f"# {arm.name} — generated by inspect_rig.py. Throwaway; safe to purge.",
        "[workload]",
        f'name = "{arm.name}"',
        "enabled = false",
        "",
        "[vm]",
        f'local_image = "{BASE_IMAGE}"',
        "vcpus = 1",
        'memory = "768M"',
        'user = "workload"',
        "rollback_keep = 1",
        "",
        "[vm.network]",
        'egress = "filtered"',
        f'allow = ["{DNS_ALLOW}"]',
    ]
    if arm.proxy:
        lines.append(f'hosts = ["{PROXY_HOST}"]')
    return "\n".join(lines) + "\n"


def deploy():
    say("== deploying two guests ==")
    for arm in ARMS:
        d = Path("/etc/workloads.d") / arm.name
        d.mkdir(parents=True, exist_ok=True)
        (d / "workload.toml").write_text(toml_for(arm))
    for arm in ARMS:
        say(f"  enabling {arm.name} ...")
        p = run(["workloadctl", "enable", arm.name], check=False, timeout=900)
        if p.returncode != 0:
            say(p.stdout[-3000:])
            say(p.stderr[-3000:])
            sys.exit(f"enable {arm.name} failed")
    say("  waiting for guests to answer ssh (first boot: cloud-init) ...")
    deadline = time.time() + 600
    pending = {a.name for a in ARMS}
    while pending and time.time() < deadline:
        for name in sorted(pending):
            r = guest(name, "echo UP", timeout=60)
            if r.returncode == 0 and "UP" in r.stdout:
                say(f"  {name} up")
                pending.discard(name)
        if pending:
            time.sleep(10)
    if pending:
        for name in sorted(pending):
            subprocess.run(["journalctl", "-u", f"workload-{name}.service",
                            "-n", "40", "--no-pager"])
        sys.exit(f"never became reachable: {sorted(pending)}")


def uid_of(name):
    return int(run(["id", "-u", f"_wl-{name}"]).stdout.strip())


def unit_prop(unit, prop):
    return run(["systemctl", "show", "-p", prop, "--value", unit]).stdout.strip()


def ruleset():
    return json.loads(run(["nft", "-j", "list", "ruleset"]).stdout)["nftables"]


def set_elements(table, name):
    """Every element of one named set/map, as printed strings."""
    for obj in ruleset():
        for kind in ("set", "map"):
            s = obj.get(kind)
            if s and s.get("name") == name and s.get("table") == table:
                return s.get("elem", [])
    return None


def guards():
    """Is the posture under test actually in force?"""
    say("== guards ==")
    for arm in ARMS:
        uid = uid_of(arm.name)
        sock = f"workload-{arm.name}-inspect.socket"

        state = unit_prop(sock, "ActiveState")
        sub = unit_prop(sock, "SubState")
        # SubState is `listening` until the first connection and `running`
        # once the socket's service is up -- both mean the socket is bound.
        # Accepting only `listening` makes the guard depend on whether a
        # probe has already run, which is not what it is asking.
        record(f"{arm.name}: inspect socket bound",
               state == "active" and sub in ("listening", "running"),
               f"{state}/{sub}")

        after = unit_prop(sock, "After")
        record(f"{arm.name}: socket ordered after setup",
               f"workload-{arm.name}-setup.service" in after,
               "present" if f"workload-{arm.name}-setup.service" in after
               else f"After={after}")

        for mapname in ("wl_inspect4", "wl_inspect6"):
            elems = set_elements("workload_proxy", mapname)
            hit = elems is not None and any(
                str(uid) in json.dumps(e) for e in elems)
            record(f"{arm.name}: {mapname} carries uid {uid}",
                   hit, "present" if hit else f"elems={elems}")

    # The tinyproxy exemption: only the proxy arm should have a cgroup element.
    # One element per inspector whose service has started (each arms its own
    # on ExecStartPre), plus the proxy workload's tinyproxy cgroup -- which is
    # the one that matters: without it the CONNECT leg is redirected into the
    # listener it was dialling past.
    cg = set_elements("workload_proxy", "wl_inspect_cg")
    n = len(cg or [])
    record("wl_inspect_cg carries at least the proxy workload's cgroup",
           n >= 1, f"{n} element(s)")


def host_can_route_v6():
    return run(["ip", "-6", "route", "get", PROBE_V6],
               check=False).returncode == 0


def temporary_v6_route():
    """Install the probe route if the host lacks one. Returns a cleanup fn."""
    if host_can_route_v6():
        return lambda: None
    run(["ip", "-6", "route", "add", PROBE_V6_NET, "dev", INSPECT_LINK])
    say(f"  (installed {PROBE_V6_NET} via {INSPECT_LINK} for the v6 probes; "
        f"this host has no IPv6 uplink)")
    return lambda: run(["ip", "-6", "route", "del", PROBE_V6_NET,
                        "dev", INSPECT_LINK], check=False)


def parse_probe(r):
    return (r.stdout or "").strip() + (("  err=" + r.stderr.strip())
                                       if r.stderr.strip() else "")


def journal_since(name, since):
    return run(["journalctl", "-u", f"workload-{name}-inspect.service",
                "--since", since, "--no-pager", "-o", "cat"],
               check=False).stdout


def probes():
    say("== probes ==")
    plain = "wlri-plain"

    r = guest(plain, "env | grep -i -E '^(https?|no)_proxy=' | wc -l")
    record(f"{plain}: guest has no proxy variables",
           r.stdout.strip() == "0", parse_probe(r))

    drop_route = temporary_v6_route()
    for label, host, port, plane in (
            ("v4 cleartext", PROBE_V4, ORIG_CLEARTEXT, "cleartext"),
            ("v4 tls", PROBE_V4, ORIG_TLS, "tls"),
            ("v6 cleartext", f"[{PROBE_V6}]", ORIG_CLEARTEXT, "cleartext"),
            ("v6 tls", f"[{PROBE_V6}]", ORIG_TLS, "tls")):
        mark = time.strftime("%Y-%m-%d %H:%M:%S")
        time.sleep(1.2)
        r = guest(plain, f"curl -sS -m 10 -o /dev/null -w '%{{http_code}}' "
                         f"http://{host}:{port}/ ; echo rc=$?", timeout=40)
        time.sleep(2)
        log = journal_since(plain, mark)
        hit = f"plane={plane}" in log and f":{PORT_CLEARTEXT if plane == 'cleartext' else PORT_TLS}" in log
        record(f"{plain}: {label} dial reaches the listener", hit,
               (log.strip().splitlines() or ["<no journal line>"])[-1]
               + f"  | curl: {parse_probe(r)}")

    drop_route()

    # The listener is socket-activated: the service should be running only
    # because a connection arrived, not because anything started it.
    st = unit_prop(f"workload-{plain}-inspect.service", "ActiveState")
    record(f"{plain}: inspect service activated by the connection",
           st == "active", st)

    # The proxy arm: the CONNECT leg is tcp dport 443 from the same uid, so
    # this is the whole test of the wl_inspect_cg exemption.
    p = "wlri-proxy"
    # Both spellings are written, so count >= 1 rather than == 1: an exact
    # count here would fail on a correct guest and hide the real question,
    # which is whether the variable is there at all.
    r = guest(p, "env | grep -ci '^https_proxy='")
    record(f"{p}: guest carries the proxy variable",
           r.stdout.strip().isdigit() and int(r.stdout.strip()) >= 1,
           parse_probe(r))
    r = guest(p, f"curl -sS -m 25 -o /dev/null -w '%{{http_code}}' "
                 f"https://{PROXY_HOST}/ ; echo ' rc='$?", timeout=60)
    ok = r.returncode == 0 and r.stdout.strip().startswith("200")
    record(f"{p}: proxied HTTPS still works through the inspector", ok,
           parse_probe(r))


def teardown():
    say("== teardown ==")
    for arm in ARMS:
        subprocess.run(["workloadctl", "disable", arm.name, "--purge"],
                       capture_output=True, text=True, timeout=300)
        shutil.rmtree(Path("/etc/workloads.d") / arm.name, ignore_errors=True)
        say(f"  purged {arm.name}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--keep", action="store_true",
                    help="leave the guests running for inspection")
    ap.add_argument("--no-deploy", action="store_true",
                    help="reuse guests left by an earlier --keep run")
    args = ap.parse_args()

    preflight()
    try:
        if not args.no_deploy:
            deploy()
        guards()
        probes()
    finally:
        if not args.keep:
            teardown()

    bad = [r for r in results if not r[1]]
    say(f"\n{len(results) - len(bad)}/{len(results)} passed")
    for label, _, detail in bad:
        say(f"  FAIL  {label}: {detail}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
