#!/usr/bin/env python3
"""Unit tests for cmd_drift's orphan detection.

cmd_drift runs the real generator into a scratch dir and diffs its output
against /run/systemd/system. The content-diff side (edited-but-not-re-enabled
units) is exercised on live hosts by tests/cli_surface. What is pinned here is
the *orphan* side — live run-files a removed workload left behind — across every
kind the generator writes into that tree: the .service units, the sysusers
.conf, and the multi-user.target.wants enablement symlink. A gap there makes
"No drift detected" a false all-clear, so each kind gets a case.

The generator is replaced by a tiny fake that writes a known "still generated"
set for one workload (`keep`); LIVE_UNITS_DIR is staged with that same set plus
a removed workload's (`gone`) leftovers.
"""

import argparse
import io
import os
import stat
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from unittest import mock


import cmd_drift  # noqa: E402


# A stand-in for generators/workload-generate: given argv[1]=services dir, emit
# the full run-file set for one still-configured workload named `keep`.
# The provenance stamp the real generator writes into every unit. Staged on both
# sides so the comparison sees a realistic unit; the version-skew cases below
# then vary the live side alone.
_KEEP_UNIT = "# Generated by workload-generate (2.0-new)\nKEEP\n"

_FAKE_GENERATOR = f"""#!/usr/bin/env python3
import os, sys
from pathlib import Path
out = Path(sys.argv[1])
(out / "multi-user.target.wants").mkdir(parents=True, exist_ok=True)
(out / "workload-keep.service").write_text({_KEEP_UNIT!r})
(out / "workload-keep.conf").write_text("u keep 10000\\n")
os.symlink("../workload-keep.service",
           out / "multi-user.target.wants" / "workload-keep.service")
"""


class OrphanDetectionTest(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory(prefix="drift-test-")
        root = Path(self._tmp.name)
        self.addCleanup(self._tmp.cleanup)

        gen = root / "fake-generate"
        gen.write_text(_FAKE_GENERATOR)
        gen.chmod(gen.stat().st_mode | stat.S_IEXEC | stat.S_IRUSR)

        self.live = root / "live"
        (self.live / "multi-user.target.wants").mkdir(parents=True)

        self.enterContext(mock.patch.object(
            cmd_drift, "_find_generator", lambda: gen))
        self.enterContext(mock.patch.object(
            cmd_drift, "LIVE_UNITS_DIR", self.live))
        self.enterContext(mock.patch.object(
            cmd_drift, "workload_config_dir", lambda: root / "cfg"))
        # Staged empty for the same reason LIVE_UNITS_DIR is staged: the real
        # /run/workload-vm exists on a hypervisor running this suite, and an
        # inspected VM's document there would make these unit-tree assertions
        # depend on what happens to be running.
        self.policy_root = root / "run-vm"
        self.policy_root.mkdir()
        self.enterContext(mock.patch.object(
            cmd_drift, "POLICY_ROOT", self.policy_root))

    def _stage_keep(self):
        """Live copy that matches what the fake generator emits (no drift)."""
        (self.live / "workload-keep.service").write_text(_KEEP_UNIT)
        (self.live / "workload-keep.conf").write_text("u keep 10000\n")
        os.symlink("../workload-keep.service",
                   self.live / "multi-user.target.wants" / "workload-keep.service")

    def _stage_gone(self):
        """Leftovers of a workload removed from config (no generated match)."""
        (self.live / "workload-gone.service").write_text("GONE\n")
        (self.live / "workload-gone.conf").write_text("u gone 10001\n")
        os.symlink("../workload-gone.service",
                   self.live / "multi-user.target.wants" / "workload-gone.service")

    def _run(self, workload=None):
        args = argparse.Namespace(workload=workload, json=False)
        out = io.StringIO()
        code = None
        try:
            with redirect_stdout(out):
                cmd_drift.cmd_drift(args, manager=None)
        except SystemExit as e:
            code = e.code
        return code, out.getvalue()

    def test_no_orphans_reports_in_sync(self):
        self._stage_keep()
        code, out = self._run()
        self.assertEqual(code, 0)
        self.assertIn("No drift", out)

    def test_older_build_stamp_alone_is_not_drift(self):
        """A live unit written by an older build, byte-identical otherwise.

        drift answers "do the running units match what this TOML would produce".
        Which build wrote them is a different question — units_from_other_build()
        answers it, and doctor/diagnose report it on their own line. If the stamp
        counted here, every workload on the host would read as drifted after
        every RPM upgrade, including the ones whose unit body did not move.
        """
        self._stage_keep()
        (self.live / "workload-keep.service").write_text(
            "# Generated by workload-generate (1.0-old)\nKEEP\n")
        code, out = self._run()
        self.assertEqual(code, 0)
        self.assertIn("No drift", out)

    def test_unstamped_live_unit_is_not_drift_either(self):
        # Upgrading from a build that predates the stamp: the comment is there,
        # the version is not. Still not a content difference.
        self._stage_keep()
        (self.live / "workload-keep.service").write_text(
            "# Generated by workload-generate\nKEEP\n")
        code, out = self._run()
        self.assertEqual(code, 0)
        self.assertIn("No drift", out)

    def test_body_drift_still_reported_under_an_older_stamp(self):
        # The normalization must not swallow a real difference that arrives
        # alongside a build bump.
        self._stage_keep()
        (self.live / "workload-keep.service").write_text(
            "# Generated by workload-generate (1.0-old)\nKEEP-BUT-EDITED\n")
        code, out = self._run()
        self.assertEqual(code, 1)
        self.assertIn("workload-keep.service", out)

    def test_orphan_service_reported(self):
        self._stage_keep()
        self._stage_gone()
        code, out = self._run()
        self.assertEqual(code, 1)
        self.assertIn("workload-gone.service", out)
        self.assertNotIn("workload-keep.service", out)   # still generated

    def test_orphan_sysusers_conf_reported(self):
        # The .conf is the kind the old glob-only scan missed entirely.
        self._stage_keep()
        (self.live / "workload-gone.conf").write_text("u gone 10001\n")
        code, out = self._run()
        self.assertEqual(code, 1)
        self.assertIn("workload-gone.conf", out)

    def test_orphan_wants_symlink_reported(self):
        self._stage_keep()
        os.symlink("../workload-gone.service",
                   self.live / "multi-user.target.wants" / "workload-gone.service")
        code, out = self._run()
        self.assertEqual(code, 1)
        self.assertIn("multi-user.target.wants/workload-gone.service", out)

    def test_missing_wants_symlink_reported(self):
        # Generator wants the enablement symlink but the live tree lacks it —
        # the workload would not auto-start on boot (owned-but-missing).
        (self.live / "workload-keep.service").write_text(_KEEP_UNIT)
        (self.live / "workload-keep.conf").write_text("u keep 10000\n")
        # deliberately omit multi-user.target.wants/workload-keep.service
        code, out = self._run()
        self.assertEqual(code, 1)
        self.assertIn("multi-user.target.wants/workload-keep.service", out)

    def test_dangling_enablement_symlink_not_reported_missing(self):
        # Regression: a present-but-dangling enablement symlink (its target
        # moved/removed) must NOT be reported as a missing symlink. The link
        # file exists, so enablement is present even though exists() follows the
        # link to a nonexistent target and returns False.
        (self.live / "workload-keep.service").write_text(_KEEP_UNIT)
        (self.live / "workload-keep.conf").write_text("u keep 10000\n")
        os.symlink("../does-not-exist.service",
                   self.live / "multi-user.target.wants" / "workload-keep.service")
        code, out = self._run()
        self.assertEqual(code, 0)
        self.assertNotIn("missing enablement symlink", out)

    def test_missing_sysusers_conf_reported(self):
        self._stage_keep()
        (self.live / "workload-keep.conf").unlink()
        code, out = self._run()
        self.assertEqual(code, 1)
        self.assertIn("workload-keep.conf", out)

    def test_collect_drift_returns_tuples(self):
        # The collector API doctor consumes: (filename, live, gen) tuples,
        # no printing, no SystemExit.
        self._stage_keep()
        self._stage_gone()
        diffs = cmd_drift.collect_drift(None)
        names = [fname for fname, _, _ in diffs]
        self.assertIn("workload-gone.service", names)
        self.assertNotIn("workload-keep.service", names)
        for _, live, gen in diffs:
            self.assertIsInstance(live, str)
            self.assertIsInstance(gen, str)

    def test_workload_filter_scopes_orphans(self):
        # Filtering to the still-present workload hides an unrelated orphan.
        self._stage_keep()
        self._stage_gone()
        code, out = self._run(workload="keep")
        self.assertEqual(code, 0)
        self.assertNotIn("gone", out)


if __name__ == "__main__":
    unittest.main()
