#!/usr/bin/env python3
"""Tests for the RPM %post install/upgrade scriptlet (rpm/workloadctl.spec).

The part under test is the upgrade warning. %post does not regenerate units, so
after `dnf upgrade workloadctl` the running workloads keep the units the
*previous* build wrote, indefinitely, until a reboot or an explicit re-enable.
On a bootc host that window cannot open — new code is only live after a reboot,
which re-runs workload-generate — but on a plain-RPM host it stays open and used
to be completely silent. Q1 Gap 3.

Each generated unit carries `# Generated by workload-generate (<NEVR>)`, so the
skew is a string compare. What has to hold:
  * fresh install ($1 == 1) never warns, whatever is on disk;
  * upgrade with units from the new build never warns;
  * upgrade with units from an older build warns and counts them;
  * every path exits 0 — a warning must not fail the transaction.

Same approach as test_rpm_postun: extract the scriptlet body from the spec and
run it under /bin/sh with the unit directory pointed at a temp dir, PATH stubs
for the commands it would otherwise run for real, and the version macro
substituted the way rpmbuild would substitute it.
"""

import os
import re
import subprocess
import tempfile
import unittest
from pathlib import Path

SPEC = Path(__file__).resolve().parent.parent / "rpm" / "workloadctl.spec"
REAL_UNIT_GLOB = "/run/systemd/system/workload-*.service"
REAL_FIREWALL_CMD = "/usr/bin/firewall-cmd"
VERSION_MACRO = "%{version}-%{release}"

NEW = "0.1.0-1.20260729120000"
OLD = "0.1.0-1.20260725211104"

_SECTION_RE = re.compile(
    r"^%(files|changelog|package|description|prep|build|install|check|clean"
    r"|post|posttrans|pretrans|preun|pre|trigger|verifyscript)\b"
)


def _extract_post_body() -> str:
    """Return the shell body of %post (RPM %macro lines stripped)."""
    lines = SPEC.read_text().splitlines()
    start = next(i for i, line in enumerate(lines) if line.strip() == "%post")
    body = []
    for line in lines[start + 1:]:
        if _SECTION_RE.match(line):
            break
        if line.lstrip().startswith("%"):
            continue  # RPM macro line, not shell
        body.append(line)
    return "\n".join(body)


class TestPostUpgradeWarning(unittest.TestCase):

    def setUp(self):
        self._tmp = tempfile.mkdtemp()
        tmp = Path(self._tmp)

        self._units = tmp / "run-systemd-system"
        self._units.mkdir()

        bin_dir = tmp / "bin"
        bin_dir.mkdir()
        # systemd-tmpfiles --create would really create directories on the test
        # host; firewall-cmd would really reload the developer's firewall.
        for name in ("systemd-tmpfiles", "firewall-cmd"):
            stub = bin_dir / name
            stub.write_text("#!/bin/sh\nexit 0\n")
            stub.chmod(0o755)
        self._bin_dir = bin_dir

        body = _extract_post_body()
        body = body.replace(REAL_UNIT_GLOB, f"{self._units}/workload-*.service")
        self.assertNotIn(REAL_UNIT_GLOB, body)
        body = body.replace(REAL_FIREWALL_CMD, str(bin_dir / "firewall-cmd"))
        self.assertNotIn(REAL_FIREWALL_CMD, body)
        # rpmbuild expands this before the shell ever sees it.
        self.assertIn(VERSION_MACRO, body,
                      "the version compare lost its macro — the warning would "
                      "then fire on every upgrade or never")
        body = body.replace(VERSION_MACRO, NEW)
        self._script = body

    def tearDown(self):
        import shutil
        shutil.rmtree(self._tmp, ignore_errors=True)

    def _unit(self, name, version):
        (self._units / f"workload-{name}.service").write_text(
            f"# Generated by workload-generate ({version})\n"
            "[Unit]\nDescription=x\n")

    def _run(self, arg):
        env = dict(os.environ)
        env["PATH"] = f"{self._bin_dir}:{env['PATH']}"
        proc = subprocess.run(
            ["/bin/sh", "-s", arg],
            input=self._script, text=True, env=env, capture_output=True)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        return proc.stderr

    # ── fresh install ($1 == 1) ──────────────────────────────────────────────

    def test_fresh_install_never_warns(self):
        """Units from an older build can exist at install time on a host that
        had the package removed and reinstalled. $1 == 1 is not an upgrade and
        must stay silent."""
        self._unit("alloy", OLD)
        self.assertNotIn("workloadctl:", self._run("1"))

    def test_fresh_install_with_no_units_is_silent(self):
        self.assertEqual(self._run("1").strip(), "")

    # ── upgrade ($1 >= 2) ────────────────────────────────────────────────────

    def test_upgrade_with_no_live_units_is_silent(self):
        """Nothing is running — there is no skew to report and nothing for the
        operator to do."""
        self.assertEqual(self._run("2").strip(), "")

    def test_upgrade_with_current_units_is_silent(self):
        self._unit("alloy", NEW)
        self._unit("dev-vnc", NEW)
        self.assertEqual(self._run("2").strip(), "")

    def test_upgrade_with_stale_units_warns_and_counts_them(self):
        self._unit("alloy", OLD)
        self._unit("dev-vnc", OLD)
        self._unit("llama-swap", NEW)
        stderr = self._run("2")
        self.assertIn("2 running workload unit(s)", stderr)
        self.assertIn("workloadctl enable", stderr)
        self.assertIn("doctor", stderr)

    def test_unstamped_units_are_not_counted(self):
        """A unit with no provenance line at all isn't ours to reason about —
        counting it would warn on hosts with hand-written workload-*.service
        files."""
        (self._units / "workload-handwritten.service").write_text(
            "[Unit]\nDescription=x\n")
        self.assertEqual(self._run("2").strip(), "")

    def test_warning_goes_to_stderr_not_stdout(self):
        self._unit("alloy", OLD)
        env = dict(os.environ)
        env["PATH"] = f"{self._bin_dir}:{env['PATH']}"
        proc = subprocess.run(
            ["/bin/sh", "-s", "2"],
            input=self._script, text=True, env=env, capture_output=True)
        self.assertEqual(proc.stdout.strip(), "")
        self.assertIn("workloadctl:", proc.stderr)


class TestPostSpecText(unittest.TestCase):
    """Guards on the literal scriptlet, so a reformat can't silently invert the
    upgrade guard or make a warning able to fail the transaction."""

    def test_guarded_on_upgrade_only(self):
        self.assertIn('if [ "$1" -ge 2 ]; then', _extract_post_body())

    def test_the_count_cannot_abort_the_transaction(self):
        """`set -e` isn't in effect in an RPM scriptlet, but the exit status of
        the last command in %post is, so the pipeline needs its own fallback."""
        self.assertIn("|| stale=0", _extract_post_body())


if __name__ == "__main__":
    unittest.main()
