#!/usr/bin/env python3
"""Unit tests for lib/unit_file.py — the typed systemd unit-file builder."""

import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "lib"))
from unit_file import Unit, Section


class TestSection(unittest.TestCase):
    def test_set_is_single_valued_and_updates_in_place(self):
        sec = Section("Service")
        sec.set("Type", "exec")
        sec.set("User", "bob")
        sec.set("Type", "notify")  # overrides, keeps original position
        self.assertEqual(sec._body(), ["Type=notify", "User=bob"])

    def test_add_is_repeatable(self):
        sec = Section("Service")
        sec.add("ExecStartPre", "a")
        sec.add("ExecStartPre", "b")
        self.assertEqual(sec._body(), ["ExecStartPre=a", "ExecStartPre=b"])

    def test_add_and_set_coexist(self):
        sec = Section("Unit")
        sec.set("Description", "x").add("After", "one").add("After", "two")
        self.assertEqual(
            sec._body(), ["Description=x", "After=one", "After=two"]
        )

    def test_value_is_stringified(self):
        sec = Section("Service")
        sec.set("CPUWeight", 200)
        self.assertEqual(sec._body(), ["CPUWeight=200"])

    def test_comment_and_blank_interleave(self):
        sec = Section("Service")
        sec.set("Type", "exec").blank().comment("group").add("ExecStart", "run")
        self.assertEqual(
            sec._body(), ["Type=exec", "", "# group", "ExecStart=run"]
        )

    def test_edge_blanks_trimmed_interior_kept(self):
        sec = Section("Service")
        sec.blank().set("A", "1").blank().set("B", "2").blank()
        # leading + trailing blank dropped, interior one kept
        self.assertEqual(sec._body(), ["A=1", "", "B=2"])

    def test_empty_comment_renders_bare_hash(self):
        sec = Section("Service")
        sec.comment()
        self.assertEqual(sec._body(), ["#"])

    def test_fluent_chaining_returns_self(self):
        sec = Section("Service")
        self.assertIs(sec.set("A", "1"), sec)
        self.assertIs(sec.add("B", "2"), sec)
        self.assertIs(sec.comment("c"), sec)
        self.assertIs(sec.blank(), sec)


class TestUnit(unittest.TestCase):
    def test_section_create_or_get_returns_same_object(self):
        u = Unit()
        a = u.section("Service")
        b = u.section("Service")
        self.assertIs(a, b)

    def test_sections_render_in_first_seen_order(self):
        u = Unit()
        u.section("Unit").set("Description", "d")
        u.section("Install").set("WantedBy", "multi-user.target")
        u.section("Service").set("Type", "exec")
        # Service was referenced after Install, so Install precedes it
        text = u.render()
        self.assertLess(text.index("[Unit]"), text.index("[Install]"))
        self.assertLess(text.index("[Install]"), text.index("[Service]"))

    def test_incremental_section_fill(self):
        u = Unit()
        u.section("Service").set("Type", "exec")
        u.section("Unit").set("Description", "d")
        u.section("Service").add("ExecStart", "run")  # back to Service
        self.assertEqual(
            u.render(),
            "[Service]\n"
            "Type=exec\n"
            "ExecStart=run\n"
            "\n"
            "[Unit]\n"
            "Description=d\n",
        )

    def test_one_blank_between_sections_and_trailing_newline(self):
        u = Unit()
        u.section("Unit").set("Description", "d")
        u.section("Service").set("Type", "exec")
        u.section("Install").set("WantedBy", "multi-user.target")
        self.assertEqual(
            u.render(),
            "[Unit]\n"
            "Description=d\n"
            "\n"
            "[Service]\n"
            "Type=exec\n"
            "\n"
            "[Install]\n"
            "WantedBy=multi-user.target\n",
        )

    def test_preamble_comments_precede_first_section(self):
        u = Unit()
        u.comment("Rootless workload service for x")
        u.comment("Generated by workload-generate")
        u.section("Unit").set("Description", "x")
        self.assertEqual(
            u.render(),
            "# Rootless workload service for x\n"
            "# Generated by workload-generate\n"
            "\n"
            "[Unit]\n"
            "Description=x\n",
        )

    def test_empty_unit_renders_single_newline(self):
        self.assertEqual(Unit().render(), "\n")

    def test_empty_section_renders_header_only(self):
        u = Unit()
        u.section("Install")
        self.assertEqual(u.render(), "[Install]\n")

    def test_render_reproduces_grouped_service_block(self):
        # Mirrors the real generator's [Service] grouping: directives split
        # into blank-separated groups with an inline comment.
        u = Unit()
        u.comment("Rootless workload service for demo")
        svc = u.section("Service")
        svc.set("Type", "exec").set("User", "_wl-demo")
        svc.blank()
        svc.comment("Load encrypted credentials")
        svc.add("LoadCredentialEncrypted", "api-key:/etc/credstore.encrypted/api-key")
        svc.blank()
        svc.add("ExecStart", '/usr/bin/podman run --name "x" "img"')
        self.assertEqual(
            u.render(),
            "# Rootless workload service for demo\n"
            "\n"
            "[Service]\n"
            "Type=exec\n"
            "User=_wl-demo\n"
            "\n"
            "# Load encrypted credentials\n"
            "LoadCredentialEncrypted=api-key:/etc/credstore.encrypted/api-key\n"
            "\n"
            'ExecStart=/usr/bin/podman run --name "x" "img"\n',
        )


if __name__ == "__main__":
    unittest.main()
