#!/usr/bin/env python3
"""Tests for the RPM %post install/upgrade scriptlet (rpm/workloadctl.spec).

The part under test is the upgrade warning. %post does not regenerate units, so
after `dnf upgrade workloadctl` the running workloads keep the units the
*previous* build wrote, indefinitely, until a reboot or an explicit re-enable.
On a bootc host that window cannot open — new code is only live after a reboot,
which re-runs workload-generate — but on a plain-RPM host it stays open and used
to be completely silent. Q1 Gap 3.

Each generated unit carries `# Generated by workload-generate (<NEVR>)`, so the
skew is a string compare. What has to hold:
  * fresh install ($1 == 1) never warns, whatever is on disk;
  * upgrade with units from the new build never warns;
  * upgrade with units from an older build warns and counts them;
  * every path exits 0 — a warning must not fail the transaction.

Same approach as test_rpm_postun: extract the scriptlet body from the spec and
run it under /bin/sh with the unit directory pointed at a temp dir, PATH stubs
for the commands it would otherwise run for real, and the version macro
substituted the way rpmbuild would substitute it.
"""

import os
import re
import subprocess
import tempfile
import unittest
from pathlib import Path

SPEC = Path(__file__).resolve().parent.parent / "rpm" / "workloadctl.spec"
REAL_UNIT_GLOB = "/run/systemd/system/workload-*.service"
REAL_FIREWALL_CMD = "/usr/bin/firewall-cmd"
VERSION_MACRO = "%{version}-%{release}"

# Absolute paths %post probes with `[ -x ... ]` to decide whether a tool is
# installed. Each must be redirected at a stub, or the probe succeeds on any
# host that really has the tool and the branch below it runs for real.
REAL_TOOL_PROBES = ("/usr/sbin/semanage", "/usr/sbin/semodule")

# Everything %post invokes by bare name, which PATH decides. Stubbed rather
# than allowed through: `semanage fcontext -a` edits the host's SELinux policy
# store, and `semodule -i` loads a policy module into it. Neither is something
# a unit test may do to the machine running it.
STUBBED_COMMANDS = (
    "systemd-tmpfiles", "firewall-cmd", "semanage", "semodule", "restorecon",
)

NEW = "0.1.0-1.20260729120000"
OLD = "0.1.0-1.20260725211104"

_SECTION_RE = re.compile(
    r"^%(files|changelog|package|description|prep|build|install|check|clean"
    r"|post|posttrans|pretrans|preun|pre|trigger|verifyscript)\b"
)


def _extract_post_body() -> str:
    """Return the shell body of %post (RPM %macro lines stripped)."""
    lines = SPEC.read_text().splitlines()
    start = next(i for i, line in enumerate(lines) if line.strip() == "%post")
    body = []
    for line in lines[start + 1:]:
        if _SECTION_RE.match(line):
            break
        if line.lstrip().startswith("%"):
            continue  # RPM macro line, not shell
        body.append(line)
    return "\n".join(body)


def _command_words(script: str) -> set[str]:
    """Words in `script` that start a command line.

    Comments and heredoc bodies are dropped first. Without that, the warning
    text this scriptlet prints supplies its own false positives — it says
    "sudo workloadctl enable" and "until units are rewritten", so `sudo` and
    `until` read as commands the script runs, and the prose above it
    contributes `build`.
    """
    words = set()
    in_heredoc = False
    for line in script.splitlines():
        if in_heredoc:
            if line.strip() == "EOF":
                in_heredoc = False
            continue
        if "<<EOF" in line:
            in_heredoc = True
        code = line.split("#", 1)[0]
        match = re.match(r"\s*([a-z][a-z0-9_-]{2,})\s", code)
        if match and f"{match.group(1)}=" not in code:
            words.add(match.group(1))
    return words


class _PostScriptletHarness(unittest.TestCase):
    """Extracts %post and runs it under /bin/sh against stubs and a temp tree.

    Base class, not a test case in its own right: two suites drive the same
    scriptlet (the upgrade warning and the fcontext registration) and both need
    it isolated from the host's policy store the same way.
    """

    def setUp(self):
        self._tmp = tempfile.mkdtemp()
        tmp = Path(self._tmp)
        self._extra_env = {}

        self._units = tmp / "run-systemd-system"
        self._units.mkdir()

        bin_dir = tmp / "bin"
        bin_dir.mkdir()
        # Every external command %post runs, replaced by a stub that records its
        # arguments and exits 0. systemd-tmpfiles --create would really create
        # directories on the test host and firewall-cmd would really reload the
        # developer's firewall, but the SELinux three are the sharp ones:
        # `semanage fcontext -a` writes a rule into the host's policy store and
        # `semodule -i` loads a module into it.
        self._stub_log = tmp / "stub.log"
        for name in STUBBED_COMMANDS:
            stub = bin_dir / name
            stub.write_text(
                '#!/bin/sh\n'
                'echo "$(basename "$0") $*" >> "$WLCTL_STUB_LOG"\n'
                'exit 0\n')
            stub.chmod(0o755)
        # semanage gets a richer stub, overriding the generic one: the fcontext
        # registration is now a three-outcome branch (added / already there /
        # genuinely failed) and the generic always-succeeds stub can only
        # exercise the first. WLCTL_SEMANAGE_ADD_ERR makes `-a` fail with that
        # text on stderr; WLCTL_FCONTEXT_STORE is the file `-l` reads back, i.e.
        # what the policy store is pretended to hold afterwards.
        (bin_dir / "semanage").write_text(
            '#!/bin/sh\n'
            'echo "semanage $*" >> "$WLCTL_STUB_LOG"\n'
            'case "$*" in\n'
            '  *"fcontext -l"*)\n'
            '      if [ -n "$WLCTL_FCONTEXT_STORE" ]; then\n'
            '          cat "$WLCTL_FCONTEXT_STORE"\n'
            '      fi\n'
            '      exit 0 ;;\n'
            'esac\n'
            'if [ -n "$WLCTL_SEMANAGE_ADD_ERR" ]; then\n'
            '    echo "$WLCTL_SEMANAGE_ADD_ERR" >&2\n'
            '    exit 1\n'
            'fi\n'
            'exit 0\n')
        (bin_dir / "semanage").chmod(0o755)
        self._bin_dir = bin_dir

        body = _extract_post_body()
        body = body.replace(REAL_UNIT_GLOB, f"{self._units}/workload-*.service")
        self.assertNotIn(REAL_UNIT_GLOB, body)
        body = body.replace(REAL_FIREWALL_CMD, str(bin_dir / "firewall-cmd"))
        self.assertNotIn(REAL_FIREWALL_CMD, body)
        # The `[ -x ... ]` probes decide whether the branch below them runs at
        # all, so redirecting them is what makes the stubs matter: left alone,
        # the probe passes on a host that has the real tool.
        for probe in REAL_TOOL_PROBES:
            body = body.replace(probe, str(bin_dir / Path(probe).name))
            self.assertNotIn(probe, body)
        # rpmbuild expands this before the shell ever sees it.
        self.assertIn(VERSION_MACRO, body,
                      "the version compare lost its macro — the warning would "
                      "then fire on every upgrade or never")
        body = body.replace(VERSION_MACRO, NEW)
        self._script = body

        # Default to a healthy policy store holding both rules, so a silent run
        # is the baseline and a suite about something else (the upgrade
        # warning) is not drowned in fcontext output. Tests about the
        # registration itself override this with their own store.
        self._fcontext_store("/var/lib/workloads(/.*)?", "/run/workload-vm(/.*)?")

    def tearDown(self):
        import shutil
        shutil.rmtree(self._tmp, ignore_errors=True)

    def _unit(self, name, version):
        (self._units / f"workload-{name}.service").write_text(
            f"# Generated by workload-generate ({version})\n"
            "[Unit]\nDescription=x\n")

    def _env(self):
        env = dict(os.environ)
        env["PATH"] = f"{self._bin_dir}:{env['PATH']}"
        env["WLCTL_STUB_LOG"] = str(self._stub_log)
        env.update(self._extra_env)
        return env

    def _semanage_add_fails(self, message):
        """Make `semanage fcontext -a` fail with `message` on stderr."""
        self._extra_env["WLCTL_SEMANAGE_ADD_ERR"] = message

    def _fcontext_store(self, *patterns):
        """Pretend the policy store already lists `patterns`."""
        store = Path(self._tmp) / "file_contexts.local"
        store.write_text("".join(
            f"{p}    all files    system_u:object_r:some_t:s0\n"
            for p in patterns))
        self._extra_env["WLCTL_FCONTEXT_STORE"] = str(store)

    def _stub_calls(self):
        if not self._stub_log.exists():
            return []
        return self._stub_log.read_text().splitlines()

    def _run(self, arg):
        proc = subprocess.run(
            ["/bin/sh", "-s", arg],
            input=self._script, text=True, env=self._env(), capture_output=True)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        return proc.stderr


class TestPostUpgradeWarning(_PostScriptletHarness):

    # ── fresh install ($1 == 1) ──────────────────────────────────────────────

    def test_fresh_install_never_warns(self):
        """Units from an older build can exist at install time on a host that
        had the package removed and reinstalled. $1 == 1 is not an upgrade and
        must stay silent."""
        self._unit("alloy", OLD)
        self.assertNotIn("workloadctl:", self._run("1"))

    def test_fresh_install_with_no_units_is_silent(self):
        self.assertEqual(self._run("1").strip(), "")

    # ── upgrade ($1 >= 2) ────────────────────────────────────────────────────

    def test_upgrade_with_no_live_units_is_silent(self):
        """Nothing is running — there is no skew to report and nothing for the
        operator to do."""
        self.assertEqual(self._run("2").strip(), "")

    def test_upgrade_with_current_units_is_silent(self):
        self._unit("alloy", NEW)
        self._unit("dev-vnc", NEW)
        self.assertEqual(self._run("2").strip(), "")

    def test_upgrade_with_stale_units_warns_and_counts_them(self):
        self._unit("alloy", OLD)
        self._unit("dev-vnc", OLD)
        self._unit("llama-swap", NEW)
        stderr = self._run("2")
        self.assertIn("2 running workload unit(s)", stderr)
        self.assertIn("workloadctl enable", stderr)
        self.assertIn("doctor", stderr)

    def test_unstamped_units_are_not_counted(self):
        """A unit with no provenance line at all isn't ours to reason about —
        counting it would warn on hosts with hand-written workload-*.service
        files."""
        (self._units / "workload-handwritten.service").write_text(
            "[Unit]\nDescription=x\n")
        self.assertEqual(self._run("2").strip(), "")

    def test_warning_goes_to_stderr_not_stdout(self):
        self._unit("alloy", OLD)
        proc = subprocess.run(
            ["/bin/sh", "-s", "2"],
            input=self._script, text=True, env=self._env(),
            capture_output=True)
        self.assertEqual(proc.stdout.strip(), "")
        self.assertIn("workloadctl:", proc.stderr)

    # ── the scriptlet must not touch the host running the test ───────────────

    def test_no_probe_survives_for_a_real_tool(self):
        """The guard that would have caught this when %post grew SELinux work.

        Each `[ -x /usr/sbin/... ]` decides whether the branch under it runs.
        semanage was left unstubbed, so on any host that has it the test ran
        `semanage fcontext -a` against the real policy store — and semanage
        reports 'already defined, modifying instead' on *stdout*, which is how
        it surfaced: as this class's stdout assertion failing on a CI runner
        while every developer machine without policycoreutils stayed green.
        """
        self.assertNotIn("[ -x /usr/", self._script,
                         "a probe for a real tool survived into the script "
                         "under test; add it to REAL_TOOL_PROBES and give it "
                         "a stub in STUBBED_COMMANDS")

    def test_every_command_it_runs_is_stubbed(self):
        """Bare command words go through PATH, so an unstubbed one finds the
        host's. Enumerated from the script rather than listed by hand, so this
        fails when %post gains a command instead of when CI does."""
        allowed = set(STUBBED_COMMANDS) | {
            # Shell builtins and coreutils the stale-unit count genuinely needs.
            "if", "then", "else", "elif", "fi", "cat", "grep", "xargs", "wc",
            "basename", "echo", "exit", "printf", "test",
            # %post's own shell function and the builtin it returns with.
            # Neither reaches PATH, so neither needs a stub — but they do read
            # as command words, and a function defined in the scriptlet is
            # exactly as safe as a builtin.
            "return", "wl_fcontext",
        }
        unknown = sorted(_command_words(self._script) - allowed)
        self.assertEqual(unknown, [], f"unstubbed command(s) in %post: {unknown}")


class TestPostFcontextRegistration(_PostScriptletHarness):
    """Registering the two host-global fcontext rules, and saying so when it
    fails.

    These used to be `semanage ... 2>/dev/null || :`, which threw away the only
    evidence a rule had not taken. A host rebuild dropped the
    /run/workload-vm(/.*)? rule, the install reported success, and the failure
    surfaced hours later at the next boot as every VM workload timing out on
    `QMP socket not ready after 60s` — a message with no SELinux in it at all.

    The awkward part, and the reason this needs its own suite: `semanage
    fcontext -a` *fails* on a rule that already exists, which is what every
    reinstall and most upgrades look like. So a nonzero exit cannot mean
    "warn", and the scriptlet has to go back and ask the store.
    """

    def test_the_selinux_rules_are_actually_registered(self):
        """The flip side of stubbing: prove the branch still runs, and runs with
        the arguments the host is meant to get. A stub that is never reached
        would make the tests above pass for the wrong reason."""
        self._run("1")
        calls = self._stub_calls()
        self.assertTrue(
            any("semanage fcontext -a -t container_file_t" in c for c in calls),
            f"%post did not register the workload tree fcontext: {calls}")
        self.assertTrue(
            any("semanage fcontext -a -t svirt_var_run_t" in c for c in calls),
            f"%post did not register the VM runtime socket fcontext: {calls}")

    def test_a_clean_registration_says_nothing(self):
        """The common path. An install that worked must stay quiet, or the
        warning is noise and gets ignored when it matters."""
        self.assertEqual(self._run("1").strip(), "")

    def test_an_already_registered_rule_is_not_reported_as_a_failure(self):
        """Reinstall and upgrade: `-a` fails, the rule is there anyway. This is
        the majority of all runs, so getting it wrong would warn on almost
        every transaction and train operators to ignore the message."""
        self._semanage_add_fails("ValueError: File context for "
                                 "/var/lib/workloads(/.*)? already defined")
        self._fcontext_store("/var/lib/workloads(/.*)?",
                             "/run/workload-vm(/.*)?")
        self.assertEqual(self._run("1").strip(), "")

    def test_a_rule_that_did_not_take_is_reported(self):
        """The outage. `-a` failed and the store does not have the rule."""
        self._semanage_add_fails("SELinux policy is not managed or store "
                                 "cannot be accessed.")
        self._fcontext_store()   # empty store: neither rule registered
        stderr = self._run("1")
        self.assertIn("could not register the SELinux fcontext rule", stderr)

    def test_a_zero_exit_is_not_taken_as_evidence_the_rule_landed(self):
        """The sharp one, and why the verdict is read from the store rather
        than from `$?`. The host this was written for came out of a rebuild
        missing one rule from a transaction that reported success — so a check
        that trusts the exit status would have passed it through exactly as
        the discarded output did.
        """
        self._fcontext_store()   # semanage exits 0, store is still empty
        stderr = self._run("1")
        self.assertIn("could not register the SELinux fcontext rule", stderr)
        self.assertIn("/run/workload-vm(/.*)?", stderr)

    def test_the_report_names_the_pattern_the_type_and_semanage_s_own_error(self):
        """Everything needed to act, in the one place anyone will ever see it.
        semanage's stderr especially: the reason is not reconstructable later,
        because nothing re-runs %post."""
        self._semanage_add_fails("cannot access the policy store")
        self._fcontext_store()
        stderr = self._run("1")
        self.assertIn("/run/workload-vm(/.*)?", stderr)
        self.assertIn("svirt_var_run_t", stderr)
        self.assertIn("cannot access the policy store", stderr)

    def test_the_report_names_the_consequence_not_just_the_rule(self):
        """The rule name means nothing to the person reading the install log.
        The symptom they will actually meet later is what makes the connection,
        so each rule carries its own."""
        self._semanage_add_fails("nope")
        self._fcontext_store()
        stderr = self._run("1")
        self.assertIn("QMP socket not ready", stderr)
        self.assertIn("rootless podman", stderr)

    def test_the_vm_consequence_names_both_domains_that_fail(self):
        """Which symptom you actually meet depends on the workload: QEMU times
        out on the QMP socket, but virtiofsd fails earlier on its pid file, so
        a VM with volumes never reaches QEMU. Verified by breaking a real host
        both ways — naming only QEMU sends half the readers looking in the
        wrong place."""
        self._semanage_add_fails("nope")
        self._fcontext_store()
        stderr = self._run("1")
        self.assertIn("QMP socket not ready", stderr)
        self.assertIn("virtiofsd", stderr)

    def test_the_report_gives_a_command_to_run(self):
        self._semanage_add_fails("nope")
        self._fcontext_store()
        stderr = self._run("1")
        self.assertIn("semanage fcontext -a -t svirt_var_run_t "
                      "'/run/workload-vm(/.*)?'", stderr)
        self.assertIn("restorecon -R /run/workload-vm", stderr)

    def test_each_rule_gets_the_restorecon_flags_its_type_needs(self):
        """-F is required under /var/lib/workloads, where both types are
        customizable and a plain restorecon silently skips them; it is wrong
        for /run/workload-vm, where neither type is. One suggestion cannot
        serve both, and the -RF form is the one that fails invisibly."""
        self._fcontext_store()
        stderr = self._run("1")
        self.assertIn("restorecon -RF /var/lib/workloads", stderr)
        self.assertIn("restorecon -R /run/workload-vm", stderr)
        self.assertNotIn("restorecon -RF /run/workload-vm", stderr)

    def test_one_rule_failing_does_not_suppress_the_other(self):
        """Each rule is registered independently and one can be present while
        the other is not — exactly the state the outage host was in."""
        self._semanage_add_fails("nope")
        self._fcontext_store("/var/lib/workloads(/.*)?")
        stderr = self._run("1")
        self.assertIn("/run/workload-vm(/.*)?", stderr)
        self.assertNotIn("/var/lib/workloads(/.*)?", stderr)

    def test_the_report_goes_to_stderr_not_stdout(self):
        """rpm folds scriptlet stdout into the transaction output where it is
        easy to lose; stderr is what dnf surfaces and journald keeps."""
        self._semanage_add_fails("nope")
        self._fcontext_store()
        proc = subprocess.run(
            ["/bin/sh", "-s", "1"],
            input=self._script, text=True, env=self._env(),
            capture_output=True)
        self.assertEqual(proc.stdout.strip(), "")
        self.assertIn("workloadctl:", proc.stderr)

    def test_a_failed_registration_cannot_fail_the_transaction(self):
        """A missing SELinux rule is a degraded install, not a broken one. The
        package still has to end up installed — an aborted transaction here
        would leave the host with no workloadctl at all."""
        self._semanage_add_fails("nope")
        self._fcontext_store()
        proc = subprocess.run(
            ["/bin/sh", "-s", "1"],
            input=self._script, text=True, env=self._env(),
            capture_output=True)
        self.assertEqual(proc.returncode, 0, proc.stderr)


class TestPostSpecText(unittest.TestCase):
    """Guards on the literal scriptlet, so a reformat can't silently invert the
    upgrade guard or make a warning able to fail the transaction."""

    def test_guarded_on_upgrade_only(self):
        self.assertIn('if [ "$1" -ge 2 ]; then', _extract_post_body())

    def test_the_count_cannot_abort_the_transaction(self):
        """`set -e` isn't in effect in an RPM scriptlet, but the exit status of
        the last command in %post is, so the pipeline needs its own fallback."""
        self.assertIn("|| stale=0", _extract_post_body())


if __name__ == "__main__":
    unittest.main()
